### ISSUE TITLE
Can no longer use a string for the gridOptions.data property

### ISSUE THREAD

**Issue by lobo78** [angular-ui/ui-grid#6155] opened 2017-04-10 23:17 UTC
As of 4.0.3, I can no longer set the value of the gridOptions.data property as a string. For 4.0.2, it works perfectly, but in 4.0.3+, the grid is not rendered.

Here is a plunker that shows the issue: [http://plnkr.co/edit/J9Xr3AuxI28FfxtYQstG](http://plnkr.co/edit/J9Xr3AuxI28FfxtYQstG)

I'm not sure, but I believe the problem is inside the dataWatchFunction, because the newData array becomes undefined here.

**Comment by RaeCai** [comment] 2017-04-17 20:56
I am facing the same issue with updating from 4.0.2 to latest version, any workaround for this?

**Comment by RaeCai** [comment] 2017-04-17 21:18
instead of using string in gridOptions.data, i am setting this value using service response. thanks for your clarification.

**Comment by paulcsiki** [comment] 2017-04-25 22:49
I had the same problem and I've replaced the string binding with an empty array that was getting updated whenever I had the data ready.

**Comment by StrangelyTyped** [comment] 2017-05-08 19:27
I've just run into this exact issue, first of all I believe that #6185 is a duplicate of this issue.

The problem was introduced [here](https://github.com/angular-ui/ui-grid/commit/56f0dc11978b9231373435d9e73da81375b5cda7#diff-d586707ee1c4e842337e09afc6ebd587L87) in v4.0.3 - where that fastWatch check was present previously it meant the newData value was provided by the scope watch instead of that block of code at the top of the function. This means that where previously the value would be extracted from scope directly it is now explicitly extracted from appScope with the following implications:

* appScope may not necessarily be the same as (or even related to) $scope. The data is pulled from appScope but the watch is attached to $scope, resolving the string expression against each of these may produce different values.
* the linked code resolving against appScope doesn't support "x.y.z" syntax, but resolving against $scope (as happens through the watches) does - #6185

I'd also like to note that the fastWatch option that features quite prominently in this area of the code doesn't appear to be documented anywhere.

**Comment by trailblazer1414** [comment] 2017-06-26 14:02
Same issue. downgraded to 4.0.2

**Comment by caseyjhol** [comment] 2017-09-06 21:24
@mportuga Thoughts?

**Comment by mportuga** [comment] 2018-02-07 15:49
My guess is that it has to do with my changes to try and reduce the number of digest cycles:
https://github.com/angular-ui/ui-grid/commit/205a2151e7d1d31dd6a78866d0413d97487769bf
https://github.com/angular-ui/ui-grid/commit/e6ab96bbae7d1ec5848a65974f5addea8e012589
https://github.com/angular-ui/ui-grid/commit/56f0dc11978b9231373435d9e73da81375b5cda7

**Comment by Joel-Kornbluh** [comment] 2018-03-14 21:56
@mportuga  this was caused by https://github.com/angular-ui/ui-grid/commit/75f98c3eda3e46f14f9d924e6f5a6d6e35bcc2b5#diff-d586707ee1c4e842337e09afc6ebd587L87

**Closed** 2018-04-02 13:05 UTC
Labels: good first issue
