### ISSUE TITLE
Possible to use different plug in for Pdf export

### ISSUE THREAD

**Issue by PrakashThiru14** [angular-ui/ui-grid#5549] opened 2016-07-14 11:40 UTC
I know, Pdfmake will not work in IE . But I need to use IE 10 browser only.. is there any other possibility to export ui-grid data to PDF, like any other  plug-in supports?

**Comment by mportuga** [comment] 2016-08-15 01:04
Moving this to our new support page as it is not a bug with UI-Grid:
https://groups.google.com/forum/#!topic/ui-grid-support/0FKtqwUGTUM

**Closed by mportuga** 2016-08-15 01:04 UTC
