### ISSUE TITLE
Colspan for Grid Header

### ISSUE THREAD

**Issue by myGitHubForum** [angular-ui/ui-grid#5178] opened 2016-03-02 02:52 UTC
I have looked at the following issue and see a few solutions which solves header template with colspan but noticed that still have few issues. If anyone can help provide the solution for the below issues.

Spanning Column Headers #644

-- All the Colspan header columns appears at the end of the table. This is messing up the order of columns I need.
-- Resizing of the columns is not working as expected.
-- Is there any different solution of headerTemplate which is simple and generic?
-- Is there any particular solution incorporated along with UI-Grid which is provided by moderators/developers?

Thanks in Advance!

**Comment by AgDude** [comment] 2016-05-09 21:07
This looks like a duplicate of #963

**Closed by AgDude** 2016-05-09 21:07 UTC
