### ISSUE TITLE
Fixed header

### ISSUE THREAD

**Issue by parliament718** [angular-ui/ui-grid#2532] opened 2015-01-11 22:52 UTC
How can I get a fixed header using this plugin (without resorting to jQuery.ui.position)?

**Comment by PaulL1** [comment] 2015-01-11 23:55
Sorry, I'm not sure I understand the question.  The header is always fixed, is it not?  What version are you using, and what are you trying to achieve?

**Comment by parliament718** [comment] 2015-01-12 01:03
I see how the question is confusing. So I would like the header to stay fixed while the BODY of the page scroll underneath, so that the window's scrollbar is used in place of the table-level one.

**Comment by PaulL1** [comment] 2015-01-14 20:31
Isn't that how the tutorials all work?  http://ui-grid.info/docs/#/tutorial/102_sorting

The header stays fixed, the body of the grid scrolls.

**Comment by JonRimmer** [comment] 2015-01-16 09:48
I believe what's being asked for is the effect demonstrated by this widget: http://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html

The table header remains attached to the top of the browser viewport so long its associated table is also inside the viewport.

**Comment by PaulL1** [comment] 2015-02-06 08:09
That's pretty cool, but not something the grid currently does.  We'd welcome a pull request that added this functionality though.

**Comment by PaulL1** [comment] 2015-05-27 06:59
I don't think this is in our roadmap, nor likely to be possible within the current grid construct and the way we scroll.  I'm pushing to 4.0 for consideration of a different UI experience there.

**Comment by manuelescamilla** [comment] 2016-01-26 15:42
Hi, I have a situation where I need the header of the columns to stay visible all the time, but as I scroll down and reach the last record, the headers of my columns will go behind my global header (fixed position).

I wonder if you have faced similar situations or if you would recommend and approach to follow.

I created one plunkr: http://plnkr.co/edit/nTO3wOQYjPdhv1rJxYyM?p=preview

As you can see below the headers of my columns are not visible after scrolling down.

![screen shot 2016-01-26 at 10 34 51 am](https://cloud.githubusercontent.com/assets/10171118/12585093/813729c8-c418-11e5-9072-fe4212bb481a.png)

Thanks a lot for any suggestion(s).

**Comment by mportuga** [comment] 2016-12-14 06:09
Closing as it is not a bug.

**Closed by mportuga** 2016-12-14 06:09 UTC
