### ISSUE TITLE
Customizer doesn't update grid.

### ISSUE THREAD

**Issue by davsan56** [angular-ui/ui-grid#4171] opened 2015-08-12 12:42 UTC
On http://ui-grid.info/customizer/, when you select a theme or change any of the values, it does not update the grid.

**Comment by JLLeitschuh** [comment] 2015-08-12 17:17
Customizer is broken. See #4173

**Comment by JLLeitschuh** [comment] 2015-08-12 17:44
Duplicate of #4079

**Closed by JLLeitschuh** 2015-08-12 17:44 UTC
