### ISSUE TITLE
Export as .csv not working on Microsoft Edge

### ISSUE THREAD

**Issue by manijak** [angular-ui/ui-grid#5184] opened 2016-03-03 12:24 UTC
Exporting to .csv works just fine on Chrome, Firefox, Safari, and IE 11, but it does not work on Microsoft Edge. Nothing happens when we click export. 

This issue is also present on your demo-site when using Edge. 
http://ui-grid.info/docs/#/tutorial/206_exporting_data

We are using version 3.1.0 of ui-grid.

**Comment by sutthoff** [comment] 2016-03-04 16:12
I'm experiencing the same issue with both 3.1.0 and 3.1.1. The problem is that the '**isIE()**' function returns Boolean, and in '**downloadFile()**' it's trying to check if 'ieVersion < 10'. 

Here's a quick fix that worked for me.

```
/**
         * @ngdoc function
         * @name isIE
         * @methodOf  ui.grid.exporter.service:uiGridExporterService
         * @description Checks whether current browser is IE and returns it's version if it is
        */
        isIE: function () {
          var match = navigator.userAgent.search(/(?:Edge|MSIE|Trident\/.*; rv:)/);
          var isIE = false;

          if (match !== -1) {
            // 2016.03.04: FIX - sutthoff - isIE doesn't return  version number? >>>
            //isIE = true;
            var userAgent = navigator.userAgent.toLowerCase();
            isIE = (userAgent.indexOf('msie') != -1) ? parseInt(userAgent.split('msie')[1]) : false;
            // <<<
          }

          return isIE;
        },
```

**Comment by KevinTCoughlin** [comment] 2016-04-05 17:19
FYI - This seems to be fixed in https://github.com/angular-ui/ui-grid/commit/17b1a0a4a4432046e5aea022265967cee60290c1, but has not made it to a release yet.

**Comment by Onumis** [comment] 2016-04-19 09:40
It does not seem to work for IE10 or IE11.
On the tutorial demo (http://ui-grid.info/docs/#/tutorial/206_exporting_data) after downloading, and inspecting the contents, I see a "sep=" pre-pended.

![image](https://cloud.githubusercontent.com/assets/1113178/14634557/5ee4641e-061a-11e6-8535-c0d36b90ce54.png)

Anyway, looking forward to have this released.

**Comment by bjaraujo** [comment] 2016-06-10 08:28
When will there be a new release of ui-grid?

**Closed** 2018-04-29 03:34 UTC
