### ISSUE TITLE
ui-grid: Storing underlying value while displaying, filtering, and sorting by label.

### ISSUE THREAD

**Issue by mgandley** [angular-ui/ui-grid#3863] opened 2015-06-25 08:28 UTC
I can't imagine this is an uncommon request.  Say we have a dataset composed of three objects:

`[task_id: 5, task_type_id: 1, task_name: "eat bread"]`
`[task_id: 11, task_type_id: 1, task_name: "compile code"]`
`[task_id: 15, task_type_id: 2, task_name: "go to store"]`

Now, let's say our `task_type_id` has an underlying definition:

`[task_type_id: 1, task_type_name: "home"]`
`[task_type_id: 2, task_type_name: "other"]`

I want to be able to create a two column table that is formatted as such:

`(col 1) - field: task_name, name: 'Task'`
`(col 2) - field: task_type_id, name: 'Task Type', display: task_type_name`

For my second column, I want all filtering, sorting, and display to be based on the `task_type_name`, but I want my underlying data to be stored as `task_type_id`.  And for the display, I want to be able to point at a pre-existing array containing all my definitions and create the mapping using what is essentially a foreign key.  The functionality I envision would be similar to the `ng-options` directive in a select control:

`<select class="form-control" name="TaskType" ng-model="task_type_id" ng-options="tasktype .task_type_id as tasktype .task_type_name for tasktype in tasktypes"></select>`

I tried using filters (`gridOptions.columnDefs.cellFilter`) and templating (`gridOptions.columnDefs.cellTemplate`), and while I got both working, they only change the display value - sorting and filtering still use the underlying numerical value.  Does anything like this exist, or is there any way of accomplishing the above (filtering, sorting, and displaying a label value while having the model store a different one)?

**Comment by imbalind** [comment] 2015-12-16 11:11
There is not a standard way to do this, but you could extend your solution by creating a custom filter and sorting function.

I'm closing this since not a bug.

**Closed by imbalind** 2015-12-16 11:11 UTC
Labels: needs: answer

**Comment by Makatun** [comment] 2018-01-19 16:44
It is a pretty standard functionality to use IDs in model and display labels on the page. Is it possible to add functionality as editDropdownOptionsArray but just for display?
