### ISSUE TITLE
Q: update a row at a time where all fields in the row are editable, and saved with a button click

### ISSUE THREAD

**Issue by tonyeung** [angular-ui/ui-grid#4090] opened 2015-07-30 21:53 UTC
I'm sorry if this has been asked, i did a quick search and didn't find anything.

The behavior I'm hoping to get implemented is where a user will click on an update button, and then all the fields for that row become editable. The update button changes to a submit button, and when clicked, i can hook into the event, get the row and send all the updates up to the server. The part I need help with is ui-grid specific, like making all the fields update-able and getting the changes

**Comment by fk-mbc** [comment] 2015-08-21 11:26
For the secound part (save all rows at one) i answered it here: https://github.com/angular-ui/ui-grid/issues/4212

**Comment by tonyeung** [comment] 2015-08-21 15:16
nice, I'm still working on finishing 1.0 of my app, but once that's done (in about a week) I'll try it out. For a moment i thought my search-fu was bad, until i saw the other question was opened recently :D

**Comment by mportuga** [comment] 2016-12-14 07:17
Closing as this is not a bug and is a bit old.

**Closed by mportuga** 2016-12-14 07:17 UTC
