### ISSUE TITLE
How to display datepicker in headerCellTemplate to filter the date

### ISSUE THREAD

**Issue by vagicharla3nadh** [angular-ui/ui-grid#2413] opened 2014-12-22 04:37 UTC
Hi
I inserted a custom filter in the grid to filter the grid data. In that in one column i need to filter the date so i want to insert the date-picker to filter the date column i inserted headerCellTemplate but date-picker is  not displaying please guide me in a right way to achieve this.
Thanks in Advance.

**Comment by ordabiadamvar** [comment] 2015-01-02 10:31
yeah my problem is this too.
i guess this will be available version 3.0 :/

**Comment by thomas-koch-comsolit** [comment] 2015-03-05 14:42
duplicate of #2796 ? close this?

**Comment by PaulL1** [comment] 2015-03-05 19:19
This one is on 2.x, so it's not quite a duplicate.  But it's unlikely to get implemented given 3.0 is coming.

**Comment by itsmefirealex** [comment] 2015-07-09 14:18
I have created datepicker as directive and i want to use in the columns. i want to filter like how age works. I can able to see the two texboxes but its not showig the datepicker as expected. but when i use "filterHeaderTemplate" outsite filters property its working but i can able place only one filterHeaderTemplate.
  
Is possible to have two headerCellTemplate in single column.. like below


columnDefs: [
	{  field: 'mixedDate', displayName: "Registered On", cellFilter: 'date:"longDate"', filterCellFiltered:true , 
		filters: [
		{ condition: uiGridConstants.filter.LESS_THAN, 
		  filterHeaderTemplate: '<div class="ui-grid-filter-container" ng-repeat="colFilter in col.filters"><input type="text" class="ui-grid-filter-input" ng-model="colFilter.term" datepicker /></div>'
		},
		{ condition: uiGridConstants.filter.GREATER_THAN, 
		  filterHeaderTemplate: '<div class="ui-grid-filter-container" ng-repeat="colFilter in col.filters"><input type="text" class="ui-grid-filter-input" ng-model="colFilter.term" datepicker /></div>'
		}] 
	}
]

**Comment by qitang** [comment] 2015-07-09 18:18
@itsmefirealex  I think so. I using created a directive that based on Jquery UI. And I put two date pickers in the same fiterheadertemplate
```javascipt
{ enableColumnResizing : false, name: "Issue Date", field: 'userDate',filters:[{ condition: checkStart}, {condition:checkEnd}],filterHeaderTemplate: '<div class="ui-grid-filter-container">from : <input style="display:inline; width:30%" date-picker type="text" ng-model="col.filters[0].term"/> to : <input style="display:inline; width:30%" date-picker type="text" ng-model="col.filters[1].term"/></div>', sortingAlgorithm: sortDate, width: '30%', cellTemplate: "<div class='ui-grid-cell-contents'>{{ row.entity.userDate|| 'N/A' }}</div>", headerCellTemplate :columnHeaderTemplate },

**Comment by surfjedi** [comment] 2016-02-03 19:49
+1

**Comment by dallincoons** [comment] 2016-03-17 23:28
+1

**Comment by anchitanc** [comment] 2016-03-22 05:16
does anyone know the solution for filter between two dates ?

**Comment by bhavesh-vyas** [comment] 2016-04-17 10:48
@anchitanc 

```
name: 'Date',
        type: 'date',
        cellFilter: 'date:"MM/dd/yyyy"',
        filterHeaderTemplate: '<div class="ui-grid-filter-container" ng-repeat="colFilter in col.filters"><input type="date" ng-model="colFilter.term" style="font-size:12px"/></div>',
        filters:
        {
        filterName: "greaterThan",
        condition: uiGridConstants.filter.GREATER_THAN,
        placeholder: 'greater than'
      },
      {
        filterName: "lessThan",
        condition: uiGridConstants.filter.LESS_THAN,
        placeholder: 'less than'
      }
```

Make sure that date column data is Date Object and not string.
if the data is not Date object, just loop through gridoptions.data and set date = new Date();

```
angular.forEach($scope.gridOptions.data, function (val) {
	val.date = new Date(val.date);
});
```

**Comment by meenakshijha** [comment] 2016-04-19 17:34
@anchitanc 

I did that using jquery date picker. Here is the code of directives and how to use it in the grid.

.directive('myCustomModalDate', function() {
  return {
    template: 'From : <input style="display:inline; width:50%"  class="ui-grid-filter-input" date-picker type="text" ng-model="col.filters[0].term"/> <br/><br/>To&nbsp;&nbsp;&nbsp;&nbsp; : <input style="display:inline;  width:50%" class="ui-grid-filter-input" date-picker type="text" ng-model="col.filters[1].term"/>',
   controller: 'SmartSearchFiltersCtrl'
  };
}) 

.directive('datePicker', function(){
    return {
        restrict : "A",
        require: 'ngModel',
        link : function(scope, element, attrs, ngModel){
            $(function(){
                $(element).datepicker({
                     changeMonth: true,
                     changeYear: true,
                     closeText: 'Clear',
                     showButtonPanel: true,
                     onClose: function () {
                        var event = arguments.callee.caller.caller.arguments[0];
                        // If "Clear" gets clicked, then really clear it
                        if ($(event.delegateTarget).hasClass('ui-datepicker-close')) {
                            $(this).val('');
                            scope.$apply(function() {
                               ngModel.$setViewValue(null);
                            });
                        }
                    },
                    onSelect: function(date){
                        scope.$apply(function() {
                           ngModel.$setViewValue(date);
                        });
                    }
               });
            })
        }
    }
})


For Grid

filters:[{ condition: checkStart}, {condition:checkEnd}], 
						 filterHeaderTemplate: '<div class="ui-grid-filter-container" class="datepick" id="date1" my-custom-modal-date></div>'

Methods

function checkStart(term, value, row, column) {
        term = term.replace(/\\/g,"");
        var now =  moment(value);
        if(term) {
        	if(moment(term).isAfter(now, 'day')) return false;
        }        
        return true;
    }

    function checkEnd(term, value, row, column) {
        term = term.replace(/\\/g,"");
        var now = moment(value);
        if(term) {
            if(moment(term).isBefore(now, 'day')) return false;
        } 
        return true;
    }

I have used Moment.js too.

Hope this helps someone!

**Comment by anchitanc** [comment] 2016-04-22 16:39
@bhavesh-vyas I tried your solution but i didnt work for me even column data are in Date for format. 
@meenakshijha i will try your solution and post the result.

**Comment by jamesdhakera** [comment] 2016-04-22 17:17
@meenakshijha  can you put this is a plunker or something. It would be really helpful, because i am unable to implement it right now

**Comment by bennettatoms** [comment] 2016-04-29 03:20
I worked up [an example plunker with ui-bootstrap datepicker](http://plnkr.co/edit/sB94q6Wap3JIi2uChybe?p=preview) that filters from and to dates, if it helps anyone.

**Comment by anchitanc** [comment] 2016-04-30 09:26
look like this plunker is not working correctly, Its not showing grid and data. Can you please check?

**Comment by bennettatoms** [comment] 2016-04-30 11:19
@anchitanc , hmmm, it's working fine for me in Chrome 49 (no errors in console, and the same code is working in my application). Are you getting errors in the console when you run it?

**Comment by jamesdhakera** [comment] 2016-05-05 09:13
@bennettatoms can u please look at this
https://github.com/angular-ui/ui-grid/issues/2196

**Comment by mportuga** [comment] 2016-08-15 00:13
I am moving all support question to our new google group for it so that we can keep the issue tracker for bugs only. You can find this discussion here:
https://groups.google.com/forum/#!topic/ui-grid-support/unyHmZ8r1w4

**Closed by mportuga** 2016-08-15 00:13 UTC
Labels: type: FAQ

**Comment by ComeOutToPlay** [comment] 2016-08-16 18:19
I wrote a solution in this [Plunkr](http://plnkr.co/edit/sUr5it4qeQZ2JTgSzlCg?p=preview) using DatePickerPopup from angular-bootstrap and condition functions from ui-grid.

If you have any comment or improvement, please let me know.

**Comment by mubashar-ali-arif** [comment] 2016-10-07 09:05
I'm trying to implement above solution 1 using angularjs, ui-grid and bootsrap, Somehow calander popup is not showing where user can pick the date range for filtering data set. No Javascript error prompt when i clicked on calendar button.

I checked and compared my script and all libraries with your plunker [link](http://plnkr.co/edit/sUr5it4qeQZ2JTgSzlCg?p=preview) all are in sync. Could you please suggest if you didn't mentioned and it's part of solution OR I'm missing something in my code.

**Comment by ComeOutToPlay** [comment] 2017-02-16 18:51
Sorry for the delay. I was not working with ui-grid until now and I did not see your question. If you have problems with the popup, it is an styling problem probably. That's why in the plunkr the example works, but in the real life (your site) maybe not.

**Comment by fcarvalllho** [comment] 2017-02-20 14:13
@ComeOutToPlay I'm using your plunkr http://plnkr.co/edit/sUr5it4qeQZ2JTgSzlCg?p=preview but I dont know why my date cant get the format "dd/MM/yyyy" when I selected the day. I already tried change all format in your plunkr but still doesn't work. You know how I can fix?
