### ISSUE TITLE
gridMenuCustomItems dynamic title

### ISSUE THREAD

**Issue by nshahpazov** [angular-ui/ui-grid#4101] opened 2015-08-03 08:46 UTC
First of all thank you for the wonderful ui.grid.
I would like to dynamic changing of a element in the gridMenu according to scope variable. In my case I have a **Enable Multiple Selection**, but when I click on it I would like it to be **Disable Multiple Selection**.

``` javascript
       gridMenuCustomItems: [{
            title: 'Disable Multiple Selection',
            action: function ($event) {
                var isMulti = $scope.gridOptions.multiSelect,
                      toggle = isMulti ? 'Disable' : 'Enable';

                $event.target.innerText = toggle + ' Multiple Selection';

                $scope.gridOptions.multiSelect = !$scope.gridOptions.multiSelect;
            },
            order: 210
        }
    ]
```

Thanks in advance.

**Comment by mportuga** [comment] 2016-12-14 07:23
Closing as this is not a bug and it is a bit old.

**Closed by mportuga** 2016-12-14 07:23 UTC
