### ISSUE TITLE
Add row reorder feature

### ISSUE THREAD

**Issue by unknown1337** [angular-ui/ui-grid#1172] opened 2014-05-07 15:09 UTC
The row move feature seems broken?

$scope.gridOptions{enableRowReordering: true};

**Comment by chrislovecnm** [comment] 2015-03-14 01:40
What is the status on this?  @junkoro does your plugin work with 3.0?

**Comment by swalters** [comment] 2015-09-16 20:53
duplicate of #1359

**Closed by swalters** 2015-09-16 20:53 UTC
Labels: type: feature
