### ISSUE TITLE
Q: defining columnDefs in the controller

### ISSUE THREAD

**Issue by tonyeung** [angular-ui/ui-grid#4124] opened 2015-08-05 20:51 UTC
This is my controller: https://gist.github.com/tonyeung/56667f6a08c314274c92

As you can see, the init is pretty bloated, but i don't really see anyway around that other than puling the definitions somewhere else. A person on the angularIRC suggested doing just that, as it would be "cleaner and shorter". While I agree that it would be shorter, i don't see any benefit to factoring that part out. The person also said that he never puts any "static data" or definitions in the controller, and creates a service for them. Which I also feel is overkill.

PS: the fields are being used by the helper to figure out which rows to display. Since I couldn't figure out how to get the filter to work on displayed text. The columns they're searching on are integers with maps to text.

PS2: suggestions on how to improve my code would also be welcome if anyone wants to give their 2 cents

**Comment by mportuga** [comment] 2016-12-14 07:39
Closing as this is not a bug.

**Closed by mportuga** 2016-12-14 07:39 UTC
