### ISSUE TITLE
Column width default to minWidth feature

### ISSUE THREAD

**Issue by twh1808** [angular-ui/ui-grid#3639] opened 2015-05-29 18:20 UTC
A team I'm working with are creating a number of different ui-grid instances. As it is currently, unless column widths are explicitly defined then all columns are calculated to take up equal space across the width of the container the grid exists in. This makes perfect sense, but was wondering if a feature could be added that states that a column should use it's `minWidth` as the default rendering `width`.

My reasoning behind this is that we're going to have upwards of 20+ grids, and I'd rather not specify `minWidth` *and* `width` for every column of every grid to match the mockups. Our grids have on average 10 columns, so that quickly adds up to ~200 lines of code. Instead, we could write 20 lines of a particular flag on each of the `gridOptions` to help cut down on coding.

The expectation I'm hoping for is something like the following scenario:
Columns 1 through 5 have `minWidth: 150px` while column 6 has `minWidth: 150px` *and* `width: '*'`. While all this sits inside of a container `1000px` wide, I would want columns 1 through 5 to take up the first `750px`, and column 6 to take up the remaining `250px`.

Unless I explicitly tell columns 1 through 5 to have `width: 150px`, then all 6 columns will be equally spaced.

**Comment by PaulL1** [comment] 2015-05-29 19:51
Why wouldn't you set width on those columns instead of minWidth?  That would do what you are asking for?

**Comment by twh1808** [comment] 2015-05-29 19:57
I've found that if `minWidth` isn't defined, you can drag the column too far (small-wise) and mess up the grid rendering (perhaps that is a different issue/bug of it's own). I can provide a Plunkr example of what I've encountered if you'd like.

In addition, one of our UI Guidelines is to always display the sort arrow of a column. If a column width is too narrow, then the sort arrow isn't viewable and the end user doesn't easily know what column(s) are currently being used for sorting. Maybe I can alter this feature request to fix the minimum width issue where the width of the text + arrow is enforced and we won't encounter a "hidden" sort arrow issue.

**Comment by PaulL1** [comment] 2015-05-29 20:06
minWidth and move is already raised as a defect: #3539.

I would have thought if you set width then the column will stay that width.  Or are you worried about users shrinking it?

**Comment by twh1808** [comment] 2015-05-29 20:13
Glad to see the other issue is being resolved.

You hit my main concern on the head. I'm worried a user will shrink a column width to a state where it's too narrow to view the column name and the arrow (if applicable). I would turn column resizing off, but another one of our requirements is to allow for resizing for instances where column data has long character values, such as a title with ~128 characters.

**Comment by twh1808** [comment] 2015-05-29 20:20
@PaulL1, I just noticed there was more to your initial response. Perhaps you updated the comment afterwards, because I missed that originally in my email.

That is definitely a possible solution, and I contemplated that. If that's the approach I must take then so be it, however I wanted to check with your team first if it was something you or others found beneficial.

**Comment by twh1808** [comment] 2015-06-09 18:40
I haven't heard a response in some time, so I've gone with the assumption that I must handle this on my own. I will let you close the Issue as you see fit.

**Comment by PaulL1** [comment] 2015-06-09 18:48
I think the issue is with resizing, I did a fix the other day where resizing wasn't honouring the col.minWidth properly.  It now does, and the default minWidth is 30.  I think in that situation you could just set the width and not the minWidth (so long as 30 is a reasonable default for your purposes).

**Comment by twh1808** [comment] 2015-06-09 18:57
In a quick review of our code, it looks on average that our `minWidth` needs to be roughly around `100px` to `120px`. Based on our database, our column names get pretty descriptive to the end user so the character length gets quite large.

Is it possible to override your `30` for the default `minWidth`? If I could just say `120px` and call it a day, then I'd be content.

**Comment by PaulL1** [comment] 2015-06-09 19:04
The defaultMinWidth isn't configurable, I guess because we let you set minWidth, so seems little point in allowing setting of defaultMinWidth.

You could write a columnBuilder that overrode it, you'd have to define that columnBuilder on each grid.  I'm pretty sure that @c0bra wrote a tutorial somewhere on using a decorator to set default gridOptions, but I can't see that right now.

Is there a reason that the option of having a gridOptions processor that you call on each of your grids before instantiation would be a problem?  That's what I do, and there are a set of options that I can avoid setting on each individual group that way.

**Comment by twh1808** [comment] 2015-06-09 19:08
No, there is no reason I can't do that.

So that we don't beat a dead horse here, that is the approach I'm going to take. We have actually already built other decorators and providers, so following that same approach again shouldn't be difficult.

I appreciate the time and conversation,
Troy

**Comment by PaulL1** [comment] 2015-11-18 07:26
Looks resolved, closing.

**Closed by PaulL1** 2015-11-18 07:26 UTC
Labels: waiting-response
