### ISSUE TITLE
Incorrect percentage in scroll events when scroll bar enabled but not shown

### ISSUE THREAD

**Issue by cwalther** [angular-ui/ui-grid#6474] opened 2017-11-21 12:51 UTC
When a grid (v4.0.11) has enableHorizontalScrollbar and enableVerticalScrollbar set to uiGridConstants.scrollbars.ALWAYS (default) and its content is high enough to require scrolling but not wide enough, so that no horizontal scroll bar is actually shown, then the scrolling percentage reported in vertical scroll events is incorrectly scaled.

http://plnkr.co/edit/ovNv8v1ibKX1KwKeIait?p=preview
Steps to reproduce: open console, scroll the grid all the way to the bottom
Expected result: output "percentage 1"
Actual result: output "percentage 0.9954257565095004"

The reason seems to be that [GridRenderContainer.getVerticalScrollLength()](https://github.com/angular-ui/ui-grid/blob/a77a7470346ce18774214862a31834fd3f0de4f5/src/js/core/factories/GridRenderContainer.js#L302) unconditionally takes into account the height of the horizontal scroll bar, whether or not it is actually there.

I am not sure how this would best be fixed. Comparing clientHeight and offsetHeight of the ui-grid-viewport seems like it would work to detect a space-occupying horizontal scroll bar, however the involved controller objects don’t seem to have direct access to the DOM elements to do that. (Note that the criterion is whether the scroll bar occupies space, not whether it is shown – it could also be overlaid on the content (system setting on macOS).)

The reduced scroll percentage output breaks detection of whether the grid is scrolled all the way to the bottom in the [ui-grid-auto-scroll](https://github.com/stevezau/ui-grid-auto-scroll) plugin.

By the way, I am a bit confused about the meaning of uiGridConstants.scrollbars.ALWAYS. From the name and from its documentation I would expect that it causes the scrollbar to be present all the time, whether or not the content requires scrolling (like overflow: scroll). What it actually does however is to make the scrollbar appear and disappear based on whether it is needed (overflow: auto), which is actually the more useful behavior. Is this the intention?

**Comment by tarzasai** [comment] 2017-11-27 11:14
I believe this is a duplicate of #6292: GridRenderContainer.needsHScrollbarPlaceholder() returns true regardless of the horizontal scrollbar being visible or not.

**Comment by cwalther** [comment] 2017-11-28 14:59
Definitely related, but not a duplicate (in the sense that it would automatically be fixed if the other were fixed) IMO – there is no needsHScrollbarPlaceholder() involved here. More like a symptom of the same underlying issue – I’m starting to believe that scrollbars.ALWAYS isn’t actually meant to behave as it does but as it says, and changing from overflow: scroll to overflow:auto in 21819c57474bf4451f3126985cfccf294c4c01e2 (which seems like a curious mixture of unrelated changes) wasn’t fully thought through.

**Comment by andrewkittredge** [comment] 2017-11-29 17:25
I might have a hacky fix for this.  

I believe the return value of needsHScrollbarPlaceholder on the pinned, 'left', container needs to change based on whether or not there is a scrollbar on the 'main' container.  Detecting the presence of the scrollbars on elements turns out to be difficult.  My approach is to compare the canvas's width to its parent's width.

I modified GridRenderContainer.prototype.needsHScrollbarPlaceholder on line 8989 of the ui-grid.js I get from npm.
`  
GridRenderContainer.prototype.needsHScrollbarPlaceholder = function () {
      if (this.name === 'left') {
          var $body = $("div[container-id=\"'body'\"]");
          var $bodyCanvas = $body.find('.ui-grid-canvas');
          return $body[0].clientWidth < $bodyCanvas[0].clientWidth;
      } else {
          return this.grid.options.enableHorizontalScrollbar && !this.hasHScrollbar && !this.grid.disableScrolling;
      }
  };
`

**Comment by mportuga** [comment] 2018-01-16 05:18
@cwalther was right and the change of making overflow: auto was certainly a mistake. Reverting that fixes 3 issues.

**Closed** 2018-01-16 05:19 UTC

**Comment by jeffantosh** [comment] 2018-01-25 23:08
After upgrading to 4.2.2, this issue is still **not** fixed.

**Comment by andrewkittredge** [comment] 2018-01-26 14:50
I concur with @jeffantosh.  I upgraded but still have the problem.

**Comment by httpete** [comment] 2018-03-07 14:28
still have the problem.
