### ISSUE TITLE
UIGRID(3.1.1) NOT YET BUILD LOCALLY

### ISSUE THREAD

**Issue by box5games** [angular-ui/ui-grid#5469] opened 2016-06-13 10:10 UTC
HI GUYS,
               I AM  A UI DEVELOPER,RECENTLY I DOWNLOAD RECENT VERSION OF UI-GRID(3.1.1) FORM THIS HUB IN MY LOCAL ENVIRONMENT.CHANGED SOME FUNCTIONALITY IN DROP DOWN MENU AND AGAIN I AM GOING TO BUILD AM FACING SOME ISSUES LIKE PHANTOMJS CREASED,UI-GRID-UTIL SERVICE THROW ERROR ,KARM ANGULAR TESTING FAILED.MAINLY I AM FACING UI-GRID-MIN .JS FILE NOT CREATED DUE THIS ERRORS.I AM CLEARLY FOLLOWING BUILDING INSTRUCTIONS FROM GIT HUB. PLEASE GIVE SOME SOLUTION FOR THIS.THANKS IN ADVANCED

**Comment by alongros** [comment] 2016-06-13 11:28
Happens to me too.
Tried to run grunt test and got this test error:
"PhantomJS 1.9.8 (Windows 7 0.0.0) uiGridCell should change a columns class when its uid changes FAILED"

and that 

LOG: 'Invalid values for originalPosition, finalPosition'

**Comment by mportuga** [comment] 2016-08-15 02:59
Moving this to our new support forum as it is not a bug with the grid.
https://groups.google.com/forum/#!topic/ui-grid-support/fWgxT09kb-Y

**Closed by mportuga** 2016-08-15 02:59 UTC
