### ISSUE TITLE
Can‘t display nested Array Data !!

### ISSUE THREAD

**Issue by 123bistami** [angular-ui/ui-grid#6439] opened 2017-10-28 22:24 UTC
Hello,

I want to display nested data in ui grid, e.g data:

[
[
{ id:1, name:“test1 },
{ id:2, name:“test2 },
{ id:3, name:“test3 },
{ id:4, name:“test4 }
],
[
{ id:5, name:“test1 },
{ id:6, name:“test2 },
{ id:7, name:“test3 },
{ id:8, name:“test4 }
]
];

idea was to fix it with rowTemplate, but i cant get the data in rowTemplate.html to use ng-repeat for the nested data, i will display multiple data in same row, i don’t want use ui grid grouping.
I think ui grid not process data if data is nested array as up, same if i will config it with celltemplate row.entity is empty and blank.
e.g. rowTemplate.html
‘<div
  ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.uid"
  ui-grid-one-bind-id-grid="rowRenderIndex + '-' + col.uid + '-cell'"
  class="ui-grid-cell"
  ng-class="{ 'ui-grid-row-header-cell': col.isRowHeader }"
  role="{{col.isRowHeader ? 'rowheader' : 'gridcell'}}"
  ui-grid-cell>
<! — Here i would like to use ng-repeat for the nested data but row.entity , colRenderIndex, col each is empty if i use {{ row.entity ... }} result is empty blank —>
</div>‘

Pls help.

**Comment by mportuga** [comment] 2017-11-11 18:01
UI-Grid was not build to support that data format. I suggest flattening the array prior to loading the data. For an example, see the following plunker using lodash:
http://plnkr.co/edit/rN32GOqng6htX2ToBTGC?p=preview

Either way, this is not an intended behavior of the grid, so I am closing this issue.

**Closed by mportuga** 2017-11-11 18:01 UTC
