### ISSUE TITLE
Keyboard events ( space click etc ) are not working on grid column headers in 3.2.9

### ISSUE THREAD

**Issue by prashanthpatha** [angular-ui/ui-grid#5809] opened 2016-11-14 12:40 UTC
Issue : keyboard events for header column click are not working.

Performing click through keyboard ( space click ) is part of accessibility. I have tried 3.2.9 version in plunker demo ( ex : http://ui-grid.info/docs/#/tutorial/401_AllFeatures ) and not able to perform sort on column header using space button on keyboard.

**Comment by mportuga** [comment] 2018-04-06 19:02
The reason for that is because the header in UI-grid is a div pretending to be a button rather than an actual button. The fix for this is to make the header into a real button.
https://github.com/angular-ui/ui-grid/blob/master/src/templates/ui-grid/uiGridHeaderCell.html#L6

**Comment by mportuga** [comment] 2018-05-15 03:48
Not reproducible on the latest version

**Closed by mportuga** 2018-05-15 03:48 UTC
Labels: good first issue
