### ISSUE TITLE
Cell validation in UI-Grid(required field, email, custom..)

### ISSUE THREAD

**Issue by p7103934** [angular-ui/ui-grid#4213] opened 2015-08-18 04:47 UTC
In one of requirement of nesting grid, we want to enable validation at column level and in case of wrong input display error message and don't allow to leave from that field.

So, can I use any third-party validation tool with UI-Grid like jquery validation or how can I implement my own logic with UI-Grid.

Can anyone, please help me out about this.

**Comment by imbalind** [comment] 2015-11-12 22:44
Duplicate of #4152

**Closed by imbalind** 2015-11-12 22:44 UTC
