### ISSUE TITLE
Misaligned columns when using pinned columns

### ISSUE THREAD

**Issue by augusto2112** [angular-ui/ui-grid#6484] opened 2017-11-28 17:57 UTC
A visual bug happens under these conditions:
 - You have a pinned column (only pinned left tested)
- The width of the shown columns are less then the length of the grid

[Here's a plunker](http://plnkr.co/edit/lPI0ksMEGbVaLytW2Fjt?p=preview), notice the last row under ID

**Comment by andrewkittredge** [comment] 2017-11-29 17:09
I suspect this a duplicate of https://github.com/angular-ui/ui-grid/issues/6474

**Comment by mportuga** [comment] 2018-01-15 22:51
I can't see the issue on Mac Chrome. Is this still reproducible for anyone? If so, what browser and OS?

**Closed** 2018-01-16 05:19 UTC
