### ISSUE TITLE
Using ng-if on grid prevents selection (v4.0.3 only)

### ISSUE THREAD

**Issue by rustygreen** [angular-ui/ui-grid#6140] opened 2017-03-29 13:59 UTC
When using an ng-if on a grid with selection enabled, in version 4.0.3, selection will be dropped.
**Steps to replicate:** Use an ng-if on a grid with selection enabled
**ui-grid version affected:** 4.0.3
**Angular Versions:** Anything under 1.5

http://plnkr.co/edit/JUYrTcI5omq6nfCFPbP0?p=preview

**Comment by mportuga** [comment] 2017-04-04 15:46
This is a duplicate of #6123

**Comment by mportuga** [comment] 2017-04-04 16:32
UI-grid version 4.0.4 is released and resolves this issue
http://plnkr.co/edit/m6XUlV8vEQRO5TufVMsH?p=preview

**Closed by mportuga** 2017-04-04 16:32 UTC
Labels: resolution: duplicate
