### ISSUE TITLE
incorrect value displayed for last row in pager/pagination

### ISSUE THREAD

**Issue by jopatz** [angular-ui/ui-grid#5944] opened 2017-01-12 12:44 UTC
The values for the last and first rows of a page are calculated correctly by `getFirstRowIndex()` and `getLastRowIndex()`.
In the template +1 is added to the result of `getFirstRowIndex()` - This is correct.
But there is also added +1 to the result of `getLastRowIndex()` - This is false because the function already returns the correct value. The addition is not needed and leads to a false display.

This happens if a non-custom pagination is used.

![image](https://cloud.githubusercontent.com/assets/13401997/21889953/b4a89f8a-d8cb-11e6-8d3b-39feef20e90e.png)

**Comment by jopatz** [comment] 2017-01-12 12:57
Used Version: 4.0.2

Issue in files since Version 4.0.0
Template: src/features/pagination/templates/pagination.html::109

**Comment by dguthrie10** [comment] 2017-01-12 13:41
The issue is in:

```javascript
                getLastRowIndex: function () {
                  if (grid.options.useCustomPagination) {
                    return publicApi.methods.pagination.getFirstRowIndex() + grid.options.paginationPageSizes[grid.options.paginationCurrentPage - 1];
                  }
                  return Math.min(grid.options.paginationCurrentPage * grid.options.paginationPageSize, grid.options.totalItems);
                },
```

This should be:
```javascript
                getLastRowIndex: function () {
                  if (grid.options.useCustomPagination) {
                    return publicApi.methods.pagination.getFirstRowIndex() + grid.options.paginationPageSizes[grid.options.paginationCurrentPage - 1];
                  }
                  return Math.min(grid.options.paginationCurrentPage * grid.options.paginationPageSize - 1, grid.options.totalItems);
                },
```

**Comment by jopatz** [comment] 2017-01-12 18:30
Why would someone do that? The issue is a simple +1 in the template that should not be there.
This problem can be fixed by changing 
`{{ 1 + paginationApi.getLastRowIndex() }} {{paginationOf}} {{grid.options.totalItems}} {{totalItemsLabel}}`
to
`{{ paginationApi.getLastRowIndex() }} {{paginationOf}} {{grid.options.totalItems}} {{totalItemsLabel}}`
in **src/features/pagination/templates/pagination.html**

There is no need to touch any functions - They are all fine and return the correct value.

**Comment by dguthrie10** [comment] 2017-01-12 21:59
Your fix is a band-aid and leavees the real problem unsolved.
Indices are zero-based. This means that, provided that getLastRowIndex() is written correctly, row 1 would display as Item 0 of ....
However, getLastRowIndex() is written wrong. It returns a 1-based 'index' - which is fine in Algol Matlab Action! Pascal and Fortran, but not in the C-like languages.
If you don't fix it there, then any other place that relies upon getting back an actual 'index will subsequently fail.

**Comment by GeorgeAnanthSoosai** [comment] 2017-01-16 21:38
any help on this ?? -- I'm getting same issue -- is there a new build which i can use ?? thank you very much for your help..

**Comment by snowf0x** [comment] 2017-01-17 21:51
i second @dguthrie10 fix here. getLastRowIndex() as it states, it should return a 0 based index.

**Comment by MurrayFurtado** [comment] 2017-01-21 14:39
Will a fix for this be available soon? It's a very glaring error!

**Comment by Shehab-Muhammad** [comment] 2017-01-27 13:24
it's a trivial false,
please fix it ASAP, I'm going to hard code it my self which's very bad solution put I'm forced as I must go live !!!!

**Comment by joeltmiller** [comment] 2017-02-21 21:29
I second this. Happened with the 4.0.0 upgrade, had to roll back to 3.2.9.

**Comment by vasyldemchuk** [comment] 2017-03-04 16:23
Any updates?

**Comment by hieudo** [comment] 2017-03-06 06:01
+1

**Comment by mportuga** [comment] 2017-03-06 16:29
Closed by this PR: https://github.com/angular-ui/ui-grid/pull/5998

**Closed by mportuga** 2017-03-06 16:29 UTC
