### ISSUE TITLE
Feature: more "modern" looking default theme for 3.0 final - maybe a bootstrap feature ?

### ISSUE THREAD

**Issue by lhwparis** [angular-ui/ui-grid#2586] opened 2015-01-18 10:17 UTC
I know everybody thinks different about design, but in my oppinion the default skin of ui-grid looks a little bit "old fashioned" what about a more modern looking default theme for the final version of 3.0? especially the gradient in table heads, all about pagination (buttons, ...) and the grid menu could be styled a little bit nicer. i know thats possible by using my own CSS but i think many people use the default one and maybe its good to update the default theme a little bit?

**Comment by PaulL1** [comment] 2015-01-19 04:46
@lhwparis: one of the limitations of the team at the moment is that we don't really have anyone who would self describe as being "front-end".  We've had ongoing difficulties with mobile, with css and look and feel stuff, and with some of the front end design.  We'd love some contributors who wanted to help with this stuff.

One option I've been mentally kicking around is an extra feature called "ui-grid-bootstrap" that would make the grid more bootstrap aware.  Particular areas for me would be using bootstrap controls for the editable feature, and making the grid play nicer inside a bootstrap framework (currently I think it overlaps the margins a little), but it would also be nice for it to pick up the bootstrap styles as well.

**Comment by timomayer** [comment] 2015-01-21 20:29
i think to use elements/styles from bootstrap is a great idea and i think 3.0 is the right milestone to do that changes in markup which will be needed for that. lloking forward to it!

**Comment by qorsmond** [comment] 2015-02-10 13:24
Don’t forget about Material Design also a matter of taste, I managed to get a theme going although not sure if it even remotely complies with the material design spec. I based it on http://materializecss.com/table.html.

![image](https://cloud.githubusercontent.com/assets/4716711/6127867/8599e594-b138-11e4-8ea0-50fcb04fea90.png)

Anyhow here is a plunk: http://plnkr.co/DG6heCZxT9HCDVPGu2cx

**Comment by JLLeitschuh** [comment] 2015-06-19 01:18
I think that the best way to handle this is to import the bootstrap less files under a namespace so that they can be used internally for our project. This would also fix some of the big cross browser issues that we seem to be having.

**Comment by PaulL1** [comment] 2015-06-19 01:35
I'd be more inclined to have a feature that had a dependency on angular-bootstrap, which would then let us use their dropdowns etc as well as the less files.

**Comment by dan2k3k4** [comment] 2016-01-13 09:13
Any news on this?

**Comment by silentFred** [comment] 2016-01-20 12:12
I would also be very interested in seeing this with bootstrap styles

**Comment by prettycode** [comment] 2016-01-29 02:31
+1 :)

**Comment by oshalygin** [comment] 2016-03-21 01:43
+1 this would be awesome.  Offering help!

**Comment by ghiscoding** [comment] 2016-06-27 20:29
Hopefully this will be implemented soon, in the mean time I took @qorsmond plunker and forked it to make it more playable with Bootstrap. So here's the [forked plunker](plnkr.co/nZEGqK)

Again thanks to @qorsmond for giving us a big start with the styling

**Note 1**: I use a 2 row height for column header. It's much better for showing long names (take a look at the last column header in the print screen below).

**Note 2** The last column isn't behaving properly, due to the Grid Menu. I haven't got time to fix it yet. If someone is nice enough to find and fix then please let me know.

Here is what it looks like (I use Bootstrap Glyphicon for showing the sorting):

![ui-grid-bootstrap](https://cloud.githubusercontent.com/assets/643976/16394396/f91ec21a-3c82-11e6-8f0d-8672180a141a.png)
 
with Header Menu (3 dots menu glyphicon onhover)

![ui-grid-bootstrap_headermenu](https://cloud.githubusercontent.com/assets/643976/16394450/45a51c06-3c83-11e6-9d53-1378ca00dd7b.png)

with Grid Menu (hamburger menu icon, same as before)

![ui-grid-bootstrap_gridmenu](https://cloud.githubusercontent.com/assets/643976/16394454/49e53b5c-3c83-11e6-90fe-a27dadabf552.png)

**Comment by ghiscoding** [comment] 2016-07-08 19:26
Would there be a way to get the work I've done eventually pushed to the UI Grid as an optional styling? I could do a PR, but I have no clue of where that would go since there is no styling options anywhere.

Could we get this going?

**Comment by JLLeitschuh** [comment] 2016-07-08 19:47
This would probably be better as a plugin.

**Comment by ghiscoding** [comment] 2016-07-18 13:51
Sorry to say but I don't really want to spend the time to learn how to create a plugin for just 1 CSS styling file. In the mean time, the Bootstrap Styling that I use is available in the plunker, which is what I now use in Production. 

If someone wants to create a plugin for it then please do.

**Comment by mportuga** [comment] 2016-08-15 00:21
Moving this to our new Google group as it is a request not a bug:
https://groups.google.com/forum/#!topic/ui-grid-support/c_USizy_fkk

**Closed by mportuga** 2016-08-15 00:21 UTC
Labels: type: enhancement

**Comment by panxq5** [comment] 2016-09-13 08:29
+1

**Comment by ThCC** [comment] 2016-10-25 10:54
Any news?

**Comment by totalard** [comment] 2017-02-11 03:05
Any Implements? How i get Bootstrap Theme for UI Grid?

**Comment by ghiscoding** [comment] 2017-02-12 04:07
@totalard perhaps if you take the time to read the entire post, you might find the answer you're looking for.

**Comment by totalard** [comment] 2017-02-12 04:30
Yeah,

I got it..
But it is not Official I think




Ashique Zakariyya P
*Sales*


Golden Square Mukkam road, Areacode PO
Malappuram Dt, Kerala - 673639
Tel: +91-483-2851331
Fax: +91-483-2851331


*Store Available at**Total Uniforms Store*
Kamala Arcade, Annie Hall Road
Calicut - 673001, Kerala
Tel: +91-495-4050403

Ph:+91-9037453581,9387474096

Visit : <http://www.total-uniforms.com>www.totaluniformstore.com
Email: totalard@gmail.com

Like Us at:     facebook.com/totalard
<https://www.facebook.com/pages/Total-Uniforms/120058738137609>
Follow us on: twitter.com/total_uniforms




DISCLAIMER: This email (including any attachments) is intended for the sole
use of the intended recipient/s and may contain material that is
CONFIDENTIAL AND PRIVATE COMPANY INFORMATION. Any review or reliance by
others or copying or distribution or forwarding of any or all of the
contents in this message is STRICTLY PROHIBITED. The opinions expressed are
those of the sender, and do not necessarily reflect those of the Company.
If you are not the intended recipient, please contact the sender by email
and delete all copies; your cooperation in this regard is appreciated.
