### ISSUE TITLE
Scroll to selected item when item is last in grid

### ISSUE THREAD

**Issue by krteter** [angular-ui/ui-grid#6717] opened 2018-05-02 20:09 UTC
I'm experiencing an issue with 4.4.4 where scrolling to a selected item is not working when the item is the last item in the list.  I've tracked the issue down to the ui-grid.core.js Grid.prototype.scrollToIfNecessary function.  For some reason, the percentage to scroll to is being calculated greater than 1.  This causes the logic to ignore the scroll request and not scroll to the item.

I've been able to work around the issue by inserting              
if (percentage > 1) { percentage = 1; }
at ui-grid.core.js line 6223.

A better solution is likely to determine why this calculation isn't correctly determining that the last indexed item is within the grid.  However, I was unable to determine this and thus did not create a pull request.

**Comment by mportuga** [comment] 2018-05-02 20:18
We’ve made changes to that logic in recent releases for sure. Could you please try it with 4.4.9 and tel me if the issue is still present, is not, I would like to close this.

**Closed** 2018-05-03 13:46 UTC
