### ISSUE TITLE
Expandable Grid Issue. Subgrid not resizing.

### ISSUE THREAD

**Issue by jdiapps** [angular-ui/ui-grid#3725] opened 2015-06-08 15:52 UTC
Navigate to the expandable grid tutorial:
http://ui-grid.info/docs/#/tutorial/216_expandable_grid

Adjust the size(smaller) of the browser so that the expandable grid gets smaller in size.
Click the Maximize button(Upper right). Notice that the expandable (subgrid) doesn't get resized.

If I manually make the browser bigger, the expandable (subgrid) resizes correctly.

**Comment by JLLeitschuh** [comment] 2015-06-13 17:37
I see what you mean. I got the same result in Chrome on OSX.
This seems to be related to the speed that the page is resized. If the grid is resized slowly the calculation seems to correctly resize the sub grid but if there is a fast jump in size the grid doesn't respond.

**Comment by swalters** [comment] 2016-01-29 16:33
duplicate of #4133 4133

**Closed by swalters** 2016-01-29 16:33 UTC
Labels: grid-expandable, type: bug
