### ISSUE TITLE
Last column disappearing upon edit 

### ISSUE THREAD

**Issue by bkirtika** [angular-ui/ui-grid#4277] opened 2015-08-27 06:52 UTC
Issue

Using a table with editing and cellnav with many columns if I scroll to the last column and edit a field in the table, the last column disappears.

version
uiGrid v3.0.5

**Comment by NivedhithaV** [comment] 2015-08-27 16:12
Facing the same issue.

**Comment by bkirtika** [comment] 2015-09-01 09:04
any updates please ??

**Comment by bkirtika** [comment] 2015-09-04 12:57
@imbalind : Hi, Is this issue solved ? Because it is not working for me. Can you help me on this, It Urgent ?

**Comment by arjunasuresh3** [comment] 2015-09-04 13:16
+1

**Comment by imbalind** [comment] 2015-09-04 13:18
@bkirtika, if you can make a plunkr with version 3.0.5 I'll give it a look

**Comment by bkirtika** [comment] 2015-09-04 13:42
link for plunker
http://plnkr.co/edit/7BbGLpE0A4Oke1633I6v?p=preview

Scroll till last and try to edit the last row.

**Comment by imbalind** [comment] 2015-09-04 14:16
on my laptop it's working fine.

I did this:

- open plnkr.
- scroll to rightmost column: File
- edited a pet and uploaded a file
- the last column is not disappearing

Are you doing anything differently?

**Comment by imbalind** [comment] 2015-09-04 14:17
btw I tried with both Chrome and Firefox, both quite up to date.

**Comment by bkirtika** [comment] 2015-09-04 14:31
Follow this procedure -
1. open plunker
2. scroll till the last row
3. try to edit registered column last row by double click (or name column)
Unable to edit

**Comment by imbalind** [comment] 2015-09-04 14:38
I'm able to edit the field you said following your steps (both *registered* and *name* columns).

Anyhow the fix I developed was about a completely different problem where the last **column** was disappearing when editing it or the one before that one.

Here it seems the problem is related to the last **row**. Am I right?

Still, I cannot reproduce it.

**Comment by bkirtika** [comment] 2015-09-04 14:45
yes right , In the last row i am unable to edit date picker (id - 499)

**Comment by bkirtika** [comment] 2015-09-08 13:57
did you get the issue ?

**Comment by imbalind** [comment] 2015-09-09 08:37
@bkirtika, as you can see, I'm unable to reproduce it:

![image](https://cloud.githubusercontent.com/assets/2514478/9757082/9bb12878-56de-11e5-9e76-b403a30c2d2e.png)

**Comment by bkirtika** [comment] 2015-09-09 08:44
Did you able to open datepicker like this on last column.

![screenshot](https://cloud.githubusercontent.com/assets/6458759/9757269/1ff3da72-56fd-11e5-9bc4-5b22fb13e681.png)

**Comment by imbalind** [comment] 2015-09-09 14:29
Ok, now I see the problem.

In my case I was not able to open the datepicker in the last two rows.

I suggest you to close this issue and open another one with a more fitting title.

Other than that I think you could give a look to the ui.grid.edit module.

**Comment by bkirtika** [comment] 2015-09-09 15:23
reference issue - https://github.com/angular-ui/ui-grid/issues/4345

**Comment by imbalind** [comment] 2015-09-12 12:51
@bkirtika I think you can close this issue now. Keeping two issue opened for the same reason doesn't seem good to me.

**Closed** 2015-09-13 07:44 UTC
Labels: PRs plz!, type: bug
