### ISSUE TITLE
How to bind controller dynamically to ui-grid

### ISSUE THREAD

**Issue by ritasakhuja** [angular-ui/ui-grid#4092] opened 2015-07-31 09:04 UTC
Hi 
We have requirement where we want to display different type of data to grid.
I want to reuse same html page with different controller containing business logic in context of data to be displayed.
When I bind controller dynamically using like
 $scope.SecondController = function () {
            return $controller('secondGridCtrl', { $scope: $scope.$new() }).constructor;
        }

I got the error of multiple directive.
Please help,so that we can use same html with different controllers

**Comment by mportuga** [comment] 2016-12-14 07:17
Closing as this is not a bug and is a bit old.

**Closed by mportuga** 2016-12-14 07:17 UTC
