### ISSUE TITLE
How to set the minimum length of a keyword for a filter.

### ISSUE THREAD

**Issue by figo2264** [angular-ui/ui-grid#4091] opened 2015-07-31 06:42 UTC
When I use the external filtering, it always sends a request to the server even though the length of the keyword is just 1.

Sometimes, it's really waste of system resource.

Is there anyway to set the minimum length of the keyword.

For example, I want to send a request to the server when the length of the keyword is more than 4 characters

**Comment by JLLeitschuh** [comment] 2015-07-31 16:12
I'm using a custom template with a filter template. The template only updates the filter value when the user presses enter in the filter input window.

**Comment by radamanth** [comment] 2015-08-20 09:30
Hi.
Do you have any example for us ? 

That would be great  !

**Comment by radamanth** [comment] 2015-08-20 10:18
As a Workaround I've specified the ng-model-options on the headerCellTemplate : 

```js
 $scope.defaultFilterTemplate = " <div class=\"ui-grid-filter-container\" ng-repeat=\"colFilter in col.filters\" ng-class=\"{'ui-grid-filter-cancel-button-hidden' : colFilter.disableCancelFilterButton === true }\"><div ng-if=\"colFilter.type !== 'select'\"><input type=\"text\" class=\"ui-grid-filter-input ui-grid-filter-input-{{$index}}\" ng-model=\"colFilter.term\" ng-model-options=\"{'updateOn': 'default blur', debounce : {'default' : 1000 , 'blur' : 0 } }\" ng-attr-placeholder=\"{{colFilter.placeholder || ''}}\" aria-label=\"{{colFilter.ariaLabel || aria.defaultFilterLabel}}\"><div role=\"button\" class=\"ui-grid-filter-button\" ng-click=\"removeFilter(colFilter, $index)\" ng-if=\"!colFilter.disableCancelFilterButton\" ng-disabled=\"colFilter.term === undefined || colFilter.term === null || colFilter.term === ''\" ng-show=\"colFilter.term !== undefined && colFilter.term !== null && colFilter.term !== ''\"><i class=\"ui-grid-icon-cancel\" ui-grid-one-bind-aria-label=\"aria.removeFilter\">&nbsp;</i></div></div><div ng-if=\"colFilter.type === 'select'\"><select class=\"ui-grid-filter-select ui-grid-filter-input-{{$index}}\" ng-model=\"colFilter.term\" ng-attr-placeholder=\"{{colFilter.placeholder || aria.defaultFilterLabel}}\" aria-label=\"{{colFilter.ariaLabel || ''}}\" ng-options=\"option.value as option.label for option in colFilter.selectOptions\"><option value=\"\"></option></select><div role=\"button\" class=\"ui-grid-filter-button-select\" ng-click=\"removeFilter(colFilter, $index)\" ng-if=\"!colFilter.disableCancelFilterButton\" ng-disabled=\"colFilter.term === undefined || colFilter.term === null || colFilter.term === ''\" ng-show=\"colFilter.term !== undefined && colFilter.term != null\"><i class=\"ui-grid-icon-cancel\" ui-grid-one-bind-aria-label=\"aria.removeFilter\">&nbsp;</i></div></div></div>";
        $scope.gridOptions.columnDefs.push(
            {name: 'reference', field: 'reference', width: 200, type: 'string', filterHeaderTemplate : $scope.defaultFilterTemplate}
```

the importante part is : 
**ng-model-options=\"{'updateOn': 'default blur', debounce : {'default' : 1000 , 'blur' : 0 } }\"**

By default I update the model 1 seconds after the event
And immediatly on blur.

If you want min-length add : 
**ng-minlength=\"3\"**

**Comment by mportuga** [comment] 2016-12-14 07:17
Closing as this is not a bug and is a bit old.

**Closed by mportuga** 2016-12-14 07:17 UTC
