### ISSUE TITLE
Firefox: Filtering menu not indented properly for columns on horizontal scroll

### ISSUE THREAD

**Issue by joshisp** [angular-ui/ui-grid#5990] opened 2017-02-07 07:02 UTC
![image](https://cloud.githubusercontent.com/assets/25604383/22681073/6816f2c8-ed31-11e6-9a74-7584f3a93544.png)

**Comment by DaAitch** [comment] 2017-02-17 17:14
duplicate of #5396

**Comment by mportuga** [comment] 2018-04-01 02:29
This is resolved on the latest issue.

**Closed by mportuga** 2018-04-01 02:29 UTC
Labels: Browser Firefox
