### ISSUE TITLE
Angular Grid Huge data points wise representation in cells with auto adjustable height 

### ISSUE THREAD

**Issue by himanshumalviya2016** [angular-ui/ui-grid#5561] opened 2016-07-18 13:42 UTC
Hello all.
      I am looking for this feature in angular grid if i have 3000 character in JSON and i want to show the data kind of this there the values are shown in points and the with of row height should be auto adjustable 
the first tow column should be pinned.
     Basically i want to show slimier look and feel of Excel sheet.
as shown the example below .

![grid](https://cloud.githubusercontent.com/assets/18567321/16916476/a81b8300-4d1a-11e6-87e8-0922bbd88d58.JPG)

please provide any plunker

**Comment by mportuga** [comment] 2016-08-15 00:45
Moving this to our new support forum as it is not a bug with UI-Grid. Someone should be able to answer it there.
https://groups.google.com/forum/#!topic/ui-grid-support/DHxQGSbkML0

**Closed by mportuga** 2016-08-15 00:45 UTC
