### ISSUE TITLE
csvExport - pinned columns do not export for 'visible' colTypes

### ISSUE THREAD

**Issue by DenAnderson** [angular-ui/ui-grid#4003] opened 2015-07-20 10:28 UTC
If you pin some columns then export the grid using 
$scope.gridApi.exporter.csvExport('visible', 'visible') or
uiGridExporterService.csvExport(grid, 'visible', 'visible')
the pinned columns aren't exported.

**Comment by PaulL1** [comment] 2015-07-20 11:09
I believe this is a duplicate of #3888.

**Closed by PaulL1** 2015-07-20 11:09 UTC
