### ISSUE TITLE
grouping numbers + groupingShowCounts=true

### ISSUE THREAD

**Issue by meyerds** [angular-ui/ui-grid#4109] opened 2015-08-03 20:28 UTC
I've been using rc.21 (pre-treeBase grouping), which has been able to sort a numeric column and show counts at the same time. v3.0.1 has trouble with sorting when counts are turned on though, as the groupingShowCounts documentation indicates.

Is it possible for this capability to be restored?

**Comment by mportuga** [comment] 2016-12-14 07:34
Closing as this is not a bug.

**Closed by mportuga** 2016-12-14 07:34 UTC
