### ISSUE TITLE
Shown grid menu causes the screen to scroll up

### ISSUE THREAD

**Issue by ingshtrom** [angular-ui/ui-grid#4523] opened 2015-10-15 13:47 UTC
You can see it here: http://ui-grid.info/docs/#/tutorial/401_AllFeatures.

If you scroll towards the top of the page, then click on the grid menu to open it, it will automatically scroll the grid to the bottom of the screen.

![ui-grid-menu-shown-scrolls-screen](https://cloud.githubusercontent.com/assets/571756/10515474/a68c3314-7321-11e5-97fc-f09a1f60aee1.png)

**Comment by deeg** [comment] 2016-01-27 22:10
Believe this is a duplicate of #4921

**Closed** 2018-03-21 16:22 UTC
