### ISSUE TITLE
Dynamic grid resizing not working for grid with too many rows

### ISSUE THREAD

**Issue by aimeehwang** [angular-ui/ui-grid#3569] opened 2015-05-22 20:44 UTC
I am trying to render grids with different heights by : <div ui-grid="gridOption" class="grid" ui-grid-cellNav ui-grid-auto-resize ui-grid-edit style="height: {{gridOption.data.length*20+52}}px"></div>

It seems fine with grid that has only 20 rows. But with Large tables that has may be 40 or 60 rows, then I can only see the border of the grid and the data is only showing the first 4 lines (everything below is empty).

I am wondering what could the underlining problem be.

**Comment by PaulL1** [comment] 2015-05-22 20:52
Grids with different heights, or grid rows with different heights?

**Comment by aimeehwang** [comment] 2015-05-22 21:08
It's grids with different heights.

**Comment by PaulL1** [comment] 2015-05-22 21:21
It sounds a little like the virtualisation threshold is getting set on the larger grids based on the smaller grids - so they're only rendering the first few rows.  But I don't really see what would cause that.  Could you provide a plunker?

**Comment by mgsstms** [comment] 2015-05-25 11:23
Official example for Expandable Grid. When you click 'Expand All', you will see only first 18 of 500 rows.

**Comment by aimeehwang** [comment] 2015-05-26 18:07
This is the plunker I just created: http://plnkr.co/edit/xK99JEMqsT7cxz8m4LxT?p=preview
You can see the table height is correct, but the table content is like being truncated.

**Comment by aimeehwang** [comment] 2015-05-26 18:09
And you can see if you try to sort the columns, all the rows will suddenly pop up.

**Comment by aimeehwang** [comment] 2015-05-27 21:13
Any thoughts?

**Comment by Jacquelin** [comment] 2015-06-03 07:12
Is this issue a duplicate of #3622 ?

**Comment by derekm** [comment] 2017-03-13 21:41
@aimeehwang -- One of your problems is you weren't including "ui.grid.autoResize" as a module dependency for your test.

Merely adding it to the top of your test's `script.js` causes the bottom table to resize (after some lag internal to ui-grid):
```
var app = angular.module('app', ['ngTouch', 'ui.grid', 'ui.grid.autoResize']);
```

I dug up this issue because I'm trying to defeat some pretty intense lag caused by ui-grid when resizing between large datasets and when showing all rows (which seems to trigger a flurry of watchers & digests & applies & animations).

**Closed** 2018-03-26 03:30 UTC
Labels: waiting-response
