### ISSUE TITLE
cellNav error

### ISSUE THREAD

**Issue by Bv202** [angular-ui/ui-grid#4035] opened 2015-07-23 06:33 UTC
Hey,

When enabling cell navigation, I'm getting this error when the grid loads:
TypeError: uiGridCtrl.focus is not a function

The keyboard navigation is NOT working. 

What's going wrong here? I'm using the latest stable version (3.0.1).

Thanks

**Comment by JLLeitschuh** [comment] 2015-07-23 16:20
This should be fixed in #3850.
However, if you have a stack trace that would be helpful.

**Comment by Bv202** [comment] 2015-07-23 16:38
Hey,

I'll see if I can post that tomorrow.

I'm getting this error when combining row select and cellnav. The reason I want both is because I want the user to navigate between certain cells to change their values. This is seperated from selecting whole rows.

**Comment by tonyeung** [comment] 2015-07-30 21:47
Here's mine, I was going to do a bit more troubleshooting but found this issue so what the hey, here it is.

The apologies on the nonsense file and row numbers, my files are concatenated and there are no sourcemaps

```
Uncaught TypeError: Cannot read property 'getNextRowCol' of undefined
module.directive.compile.pre.uiGridCtrl.cellNav.handleKeyDown @ app.js:55834
(anonymous function) @ app.js:57060
jQuery.event.dispatch @ app.js:4435
jQuery.event.add.elemData.handle @ app.js:4121
```

**Comment by tonyeung** [comment] 2015-07-30 21:57
I traced it down to cellNav not existing on the container for some reason

**Comment by tonyeung** [comment] 2015-07-31 15:42
This seems to be a separate issue, I'm going to be creating a new issues instead.
In short, cellNav works on body but not on pinned (left in this case) columns.

**Comment by tonyeung** [comment] 2015-07-31 15:48
version ui-grid - v3.0.1 - 2015-07-17

**Comment by tonyeung** [comment] 2015-07-31 15:48
building the master now to see if this issue is fixed there

**Comment by tonyeung** [comment] 2015-07-31 17:51
Built master, referenced it, still no good

**Comment by swalters** [comment] 2015-07-31 18:03
can you create a plunkr that recreates it?

**Comment by tonyeung** [comment] 2015-07-31 18:22
@swalters  thar she is: http://plnkr.co/edit/pz2gACcGc3glqCs0mZlP?p=preview

Repro by clicking on any field on the left column, press tab, nothing happens. 
Console will show error I posted.
Curiously, a second tab will bring focus over to the body container and cellnav works as expected.
The current bower version and the master version i built (which crashed over and over again until i ran grunt --force) both behave this way.

Also, I feel bad jacking this issue when I don't think its related to it, can we migrate these comments?

**Comment by swalters** [comment] 2015-07-31 19:08
I see the issue.  should have fix soon

**Comment by tonyeung** [comment] 2015-07-31 19:13
yay! i didn't waste your time. Its always embarrassing when its something stupid on my end. I was sure I had missed a flag somewhere or something.

**Comment by swalters** [comment] 2015-07-31 19:23
@tonyeung this should fix your issue.  @Bv202 you can try it also.  Might have fixed your issue as well.

**Comment by tonyeung** [comment] 2015-07-31 19:50
confirmed fixed my issue

**Closed** 2015-09-15 15:32 UTC
Labels: grid-cellNav, resolution: solved, type: bug, waiting-response
