### ISSUE TITLE
More granular in-line edit tracking

### ISSUE THREAD

**Issue by logannc** [angular-ui/ui-grid#4860] opened 2015-12-15 16:15 UTC
Particularly for the case when `rowEditWaitInterval = -1` and we wait for `flushDirtyRows()` to be called, it is helpful to highlight not only which ROWS changed, but which COLUMN on that row changed.

Currently it just sets the color of the whole dirty row to a reddish color (which is IMHO not very visible and should be closer to `#F00`), but it would be nice if we could have an additional change to the changed column (bold text, background color to light red, etc). 

A possible additional issue is that there is not an easy way to get the cell ELEMENT from the cell object (from CellNav). You can construct a monster query like `$('#' + gridApi.grid.id + '-' + gridApi.grid.getVisibleRows().indexOf(cell.row) + '-' + cell.col.uid + '-cell')`, but this is not robust. And it doesn't solve the above issue because if you set said element to have some additional CSS, it doesn't change even if the data changes.

**Comment by imbalind** [comment] 2015-12-15 16:50
I don't know a finer granularity would be always advisable, I'll leave this open to see if anyone else would be interested in it.

As for the color, it could obviously be customized by an overriding CSS.

**Comment by logannc** [comment] 2015-12-15 17:01
I imagine that tracking which column changed is never negative and often useful. You already know what is changing because you know which cell is being editted, so it shouldn't be difficult. And it can be a default `false` option to display that column differently. But I think that losing that information is, well, a loss.

And yea, I do override it. `#F00` is a terrible color, but it still makes me happy to see such a *simple* color in my code. :)

**Comment by imbalind** [comment] 2015-12-15 17:29
What you're saying is true, but for anything we add, we pay a price in terms of performance, memory usage and complexity (and people out there already says the library is too complex).

**Comment by logannc** [comment] 2015-12-15 18:53
Arguably it should be split into a core library and several plug-in libraries, though performance is not yet an issue for me (I just loaded up 26k rows and it's perfectly snappy). 

Regardless of code structure, if you just look at the 'edit' module's functionality, you could reasonably expect the ability to track changes on a row, particularly when it is often used with cellNav which suggests a shift from thinking in terms of whole rows to thinking in cells (albeit as a column of a row).

**Comment by mportuga** [comment] 2017-03-06 21:08
Since this is not a bug, I am closing this issue.

**Closed by mportuga** 2017-03-06 21:08 UTC
Labels: needs: decision, type: enhancement
