### ISSUE TITLE
Unable to download css at http://ui-grid.info/customizer/#

### ISSUE THREAD

**Issue by auyeungkt** [angular-ui/ui-grid#4165] opened 2015-08-12 00:56 UTC
Dear folks,

   Thanks for your time to read my message. I tried to custom the ui-grid CSS by using customizer (http://ui-grid.info/customizer/#).  I had tried Firefox, Chrome, and I.E. 11, but I still could not download the CSS after I had modified the color. I am wondering how can I download the CSS, or is there having other resources that similar to this customizer?

Have a nice day.

Luke

**Comment by JLLeitschuh** [comment] 2015-08-12 17:44
Duplicate of #4079

**Closed** 2015-08-12 17:46 UTC
Labels: customizer, resolution: duplicate
