### ISSUE TITLE
Hide unneeded scrollbars

### ISSUE THREAD

**Issue by matthiasnienaber** [angular-ui/ui-grid#4278] opened 2015-08-27 07:58 UTC
There is no way more unneeded scrollbars hide.

The setting enableHorizontalScrollbar: 2 
or uiGridConstants.scrollbars.WHEN_NEEDED no longer exists.

The same applies vertical scrollbars.

**Comment by c0bra** [comment] 2015-08-27 14:02
That's correct, it's not currently an option. This issue is a duplicate of #2635.

**Closed by c0bra** 2015-08-27 14:02 UTC
