### ISSUE TITLE
export csv error

### ISSUE THREAD

**Issue by HIKALU-Z** [angular-ui/ui-grid#4680] opened 2015-11-12 01:44 UTC
hi~
when i  use export as csv at **win8** sysem .
it will be messy code and can't to be read.
how can i slove this problem ?

*PS*: I use office2007 on my win8 .

**Comment by PaulL1** [comment] 2015-11-12 03:23
I think you need to provide a little more information.

Does the export as csv work on the tutorial page for you?
Have you set the "older Excel compatibility" flag?

**Comment by HIKALU-Z** [comment] 2015-11-12 03:43
yes i have already use  older Excel compatibility.
`exporterOlderExcelCompatibility: true`
it works well at my win7 computer.but did't work well at win8.
And after i changed the csv type as ANSI,it works well at win8.
i don't kown what happen.

**Comment by PaulL1** [comment] 2015-11-18 07:35
It's not really clear to me what the problem is that you are seeking a resolution to.  Can you provide more information, and perhaps a clear description of what it's doing that you consider to be unexpected behaviour?

**Comment by HIKALU-Z** [comment] 2015-11-18 09:41
i also don't kown what happen .
but it solved.
when i use office 2010 on my win8 PC ,it will work well.
when i use office 2007 it will be messy code.only i change csv type as ANSI code.it can work well.
whatever,thank you for your advice.

**Comment by PaulL1** [comment] 2015-11-18 19:37
OK, glad you sorted it out.

Closing.

**Closed by PaulL1** 2015-11-18 19:37 UTC
Labels: waiting-response
