### ISSUE TITLE
How to set the dropdown options of a column base on the value of another column

### ISSUE THREAD

**Issue by gizbo** [angular-ui/ui-grid#4087] opened 2015-07-30 17:45 UTC
Hello,
    How can I set the value of the array for the property editDropdownOptionsArray on a column.  I looking for something like 
columnDefs:[ {field:col1},
{field:col2, ..., editDropdownOptionsArray: $filter('myFilter')(col1);}
]
is this even possible? 
Thanks,
Yves

**Comment by mportuga** [comment] 2016-12-14 07:16
Closing as this is not a bug and is a bit old.

**Closed by mportuga** 2016-12-14 07:16 UTC
