### ISSUE TITLE
Column Resize Tutorial not working

### ISSUE THREAD

**Issue by jacohend** [angular-ui/ui-grid#4075] opened 2015-07-29 19:44 UTC
[Tutorial: 204 Column Resizing](http://ui-grid.info/docs/#/tutorial/204_column_resizing) is not working in Linux Mozilla Firefox v.39 or Linux Chromium v.43. No column resizing is possible.

**Comment by wiibaa** [comment] 2015-10-28 12:54
Strange... I would says it is now fixed with latest 3.x release as I cannot reproduce it under Debian Jessie with Iceweasel 38 or Chromium 45.
@jacohend  can you please retest soon

**Comment by nh1402** [comment] 2016-01-05 11:54
Doesn't work for me on Chrome 47 or Firefox 42

**Closed** 2016-12-14 07:01 UTC
