### ISSUE TITLE
How can we fix the last column resize?

### ISSUE THREAD

**Issue by kiranrajufixstream** [angular-ui/ui-grid#6728] opened 2018-05-16 12:36 UTC
Hello,

I wish to fix the last column as not beyond the table and not below the column edge, FYI attached snaps

![beyond](https://user-images.githubusercontent.com/38715425/40117144-ae52494e-5933-11e8-9202-4f5c993dc800.PNG)
![inner](https://user-images.githubusercontent.com/38715425/40117152-b633c82c-5933-11e8-920b-6f4bdcf79083.PNG)

Can't able to fix that last column..!
How can we fix this, can someone help me..

Thanks,

**Comment by zuzusik** [comment] 2018-05-16 14:29
duplicate of https://github.com/angular-ui/ui-grid/issues/6675

**Comment by mportuga** [comment] 2018-05-18 01:07
Closing as a duplicate.

**Closed by mportuga** 2018-05-18 01:07 UTC
