### ISSUE TITLE
When pinning, exporting visible data will not export pinned data

### ISSUE THREAD

**Issue by coty-crg** [angular-ui/ui-grid#4220] opened 2015-08-18 20:31 UTC
As the title says. I was trying to pin usernames to the left of a grid, then export it out as csv. If they are pinned, the column doesn't show up at all in the exported data. If not, everything is fine.

**Comment by anilnatha** [comment] 2016-02-10 18:18
Duplicate of https://github.com/angular-ui/ui-grid/issues/4220

**Comment by mportuga** [comment] 2018-05-19 16:26
No longer reproducible on latest version.

**Closed by mportuga** 2018-05-19 16:26 UTC
