### ISSUE TITLE
Allow hiding scrollbars if they are not necessary

### ISSUE THREAD

**Issue by MariMax** [angular-ui/ui-grid#2635] opened 2015-01-26 10:56 UTC
I can't hide horizontal scrollbar, even if my table is narrow [exapmle](http://plnkr.co/edit/tPER4Qwckk9AwO3sqBG3?p=preview) I can fully hide it by set enableHorizontalScrollbar = 0, but I need this scroll bar when I dynamically add columns

**Comment by herdanskecommodities** [comment] 2015-01-29 20:20
I'm having the same issue (with the latest unstable).

I wanted to try without the vertical scrollbar, but for some reason "enableVerticalScrollbar: false" on the gridOptions is being ignored (for me anyway).

If i set overflow-x: auto and overflow-y:hidden on the ui-grid-viewport div, the horizontal scrollbar works as expected: disappears if the colums can fit in the viewport and scrolling correctly if they cannot. It also fixes this weird scroll issue when you scroll all the way to the right:

![image](https://cloud.githubusercontent.com/assets/9362788/5965407/3193fcc2-a7fc-11e4-9a54-656a48d7cabd.png)

I'm no expert on dom's, so I'm not sure how to work the viewport to include the vertical scrollbar correctly.

**Comment by kolesnik** [comment] 2015-02-07 21:27
I face the same issue, any ideas how to fix it ?

**Comment by bluesky777** [comment] 2015-02-22 10:27
Same here :( any solution?

**Comment by c0bra** [comment] 2015-02-22 17:37
@herdanskecommodities Your issue should no longer occur.

WHEN_NEEDED is no longer a valid option for the enable scrollbar properties. You can still toggle whether they're on or off, though. See this plunker for an example: http://plnkr.co/edit/h7uJHM2tZ0bSqkWInjOU?p=preview

**Comment by herdanskecommodities** [comment] 2015-02-23 07:12
Hi @c0bra , and thanks for the update + poke.

It would be neat to be able to have WHEN_NEEDED as an option, but I am assuming it would be difficult to re-implement in the current version?

It's not a must-have for the system I am working on right now, I am just curious why the option was removed, and whether there is any plans for it to make a return. =)

**Comment by c0bra** [comment] 2015-02-23 15:56
@swalters may be able to comment on that; I wasn't involved in the removal but my bet is that it's difficult to re-implement with the current native scrolling, yes.

**Comment by PhilBroadbent** [comment] 2015-03-03 12:40
I think this can be solved by removing the width of the vertical scrollbar from the ui-grid-canvas width...If i have a grid which fits perfectly 
Original:
![image](https://cloud.githubusercontent.com/assets/7779879/6462552/00272e7e-c1a2-11e4-8c0d-cff8874edf71.png)

See when i remove 30px from it (width of vertical scrollbar) the horizontal bar disapears:
![image](https://cloud.githubusercontent.com/assets/7779879/6462569/24b8e444-c1a2-11e4-9151-c5c06b380467.png)

Could this be implemented @c0bra ? I have the problem that @herdanskecommodities has (yous aid it was solved but I seem to have the issue?)

**Comment by pragatir** [comment] 2015-03-04 06:35
I am using 3.0.0-rc.20 but. I still see the scrollbar issue.

**Comment by MilovanovMaxim** [comment] 2015-03-10 13:19
I do not really know should it be here or should I create a new issue, this is about column adjustment [screen](https://yadi.sk/i/-hx1tOWkf9a7C) rc.20, IE-9

**Comment by c0bra** [comment] 2015-03-11 21:22
@MilovanovMaxim you should create a new issue.

**Comment by c0bra** [comment] 2015-03-11 21:24
@pragatir Are you able to reproduce it in a plunker?

**Comment by c0bra** [comment] 2015-03-11 21:27
@PhilBroadbent it may be possible to implement it that way, yes.

**Comment by svmashok** [comment] 2015-03-12 12:50
@c0bra : As like @pragatir , me too using  3.0.0-rc.20 and facing the same issue.
Here the apis are completely changed, for horizontal scroll bar, the values are different when compared to old version.
The possible values are (from api guide) 
enableHorizontalScrollbar : 
uiGridConstants.scrollbars.ALWAYS by default. This settings controls the horizontal scrollbar for the grid. Supported values: uiGridConstants.scrollbars.ALWAYS, uiGridConstants.scrollbars.NEVER
(not like ur pluker, $scope.gridOptions.enableHorizontalScrollbar = 2;)

so no possiblity to show whenever its needed..

do u have any idea to fix this issue?

**Comment by c0bra** [comment] 2015-03-30 15:46
@svmashok Adding a "WHEN_NEEDED" option should be possible, but we'll push it to v3.1 so it's not blocking a 3.0 release.

**Comment by c0bra** [comment] 2015-03-30 15:47
@MilovanovMaxim Can you get the scroll issue to happen in IE9 in this plunker? http://plnkr.co/edit/h7uJHM2tZ0bSqkWInjOU?p=preview

**Comment by applelok** [comment] 2015-09-08 02:58
I am using v3.0.4 but I still got the same issue as @herdanskecommodities

![image](https://cloud.githubusercontent.com/assets/11794100/9725443/f1e3b606-5617-11e5-94fa-d8d78fb2c15d.png)

I have no idea what to do to fix his problem just by CSS like what @PhilBroadbent mentioned..
because i have 3 dynamic grid inside my page and NOT every grid will have so many columns which needs a horizontal scrollbar.

Will it be fixed soon? 

But anyway, thanks a lot and really appreciate what you guys did on ui-grid.

**Comment by mermonkey** [comment] 2015-11-20 23:06
I'm also looking forward to WHEN_NEEDED. 
If that gets delayed, would at least be nice to not use inline styling on ui-grid-viewport (style="overflow: scroll;"). That is forcing me to hold my nose and use the !important flag in my css...
.ui-grid-viewport {
    overflow: auto !important;
}

**Comment by lvarayut** [comment] 2015-12-27 04:45
I agree with @mermonkey. I can't overwrite the default `overflow: scroll` of the ui-grid-viewport. :(

**Comment by Gajendrasinh** [comment] 2016-01-05 05:29
if i am use
 .ui-grid-viewport {
overflow: auto !important;
}

then i can see only 15 record where i am set limit 50 how get i get all record

**Comment by mermonkey** [comment] 2016-01-14 22:17
Yes. I was doing same... until i found this issue with pinned columns :(
https://github.com/angular-ui/ui-grid/issues/4964

**Comment by AnthonyTomlin** [comment] 2016-02-08 20:48
Would there be a way to attach the scroll bars to the outside of the ui-grid box instead of within the container to eliminate the grid having to scroll past either the verticle/horizontal scroll bars to show all of the cells contents thus creating the slight mis-alignment with the headers and columns/rows

**Comment by gethinoakes** [comment] 2016-03-07 15:36
A workaround for this is to set `enableHorizontalScrollbar: 0` on your gridOptions and then in your stylesheet have the following:

```
.ui-grid .ui-grid-render-container-body .ui-grid-viewport {
    overflow-x: auto !important;
}
```

Now the horizontal scroll bar only displays when needed.

**Comment by alarm9k** [comment] 2016-10-31 13:45
If you are allowed to use flexboxes:

```
.ui-grid-render-container-body {
    .ui-grid-header {
      padding-right: 17px;

      .ui-grid-header-viewport {
        width: 100%;

        .ui-grid-header-canvas {
          width: 100%;

          .ui-grid-header-cell-wrapper {
            display: block;
            width: 100%;

            .ui-grid-header-cell-row {
              display: flex;
              min-width: 0;

              .ui-grid-header-cell {
                flex: 1 1 0;
                min-width: @col-min-width;
              }
            }
          }
        }
      }
    }

    .ui-grid-viewport {
      overflow: auto !important;
      display: flex;

      .ui-grid-canvas {
        flex: auto;
        min-width: 0;

        [role="row"] {
          display: flex;
          min-width: 0;

          .ui-grid-cell {
            flex: 1 1 0;
            min-width: @col-min-width;
          }
        }
      }
    }
  }
```

Where col-min-width is a minWidth that you would normally set in the gridOptions. Also you have to set the ui-grid-header's padding-right (which is 17px in this example) to the width of your browser's scrollbar with the javascript on certain events: number of rows changed, container resized etc. Scrollbar width = ui-grid-viewport's offsetWidth - clientWidth.

**Comment by mportuga** [comment] 2016-12-14 06:11
This is a duplicate of #1772

**Closed by mportuga** 2016-12-14 06:11 UTC
Labels: waiting-response
