### ISSUE TITLE
Grid not rendering correctly when placed in bootstrap accordion

### ISSUE THREAD

**Issue by tuckerjt07** [angular-ui/ui-grid#4096] opened 2015-07-31 20:21 UTC
The ui-grid will not render data when placed in an accordion that is defaulted to close. I haven't had much chance to dig into it but it appears to be related to the display: none property of the collapse class. The grid can be forced to rerender by calling resize, whether that is using the $interval code snippet as suggested for modals, resizing the window, opening developer tools, etc. The issue with using the provided $interval snippet is the differences in the way modals and accordions are rendered on the page. For an accordion the $interval would need to run continuously the entire time the page was open. I'm not sure if there is a "real fix" for the issue but the simplest solution would be to provide an externalization of the $scope.gridApi.core.handleWindowResize() function. I have attempted to capture this function and call it from outside of onRegisterApi but it is always undefined. I do know that having the ability to call this function would force the grid to render when the accordion was expanded.

**Comment by Vinodang** [comment] 2015-10-21 05:18
for ng-grid i think you need to call `gridOptions.ngGrid.buildColumns()`; for ui-grid you need to call `gridApi.core.refresh()`;

**Comment by mportuga** [comment] 2016-12-14 07:19
Closing as this is not a bug and is a bit old.

**Closed by mportuga** 2016-12-14 07:19 UTC
