### ISSUE TITLE
Reset column width after column move

### ISSUE THREAD

**Issue by tomaslaurutenas** [angular-ui/ui-grid#4188] opened 2015-08-14 06:59 UTC
When I change column position with mouse, this reset column width to default width.

**Comment by ingshtrom** [comment] 2015-08-20 21:39
+1 

I am seeing this too. You can see this happen in one of the tutorials: http://ui-grid.info/docs/#/tutorial/401_AllFeatures. I am seeing this on v3.0.4 with Angular v1.3.16 at work. It looks like the tutorial is using UI-Grid v3.0.4 and Angular v1.4.3.

Steps to reproduce:
1. resize the "Id" column header to an abnormally larger size
2. click+drag the "Name" column header to the right of the "Age" column header

Expected: the "Name" and "Age" column headers switch places while the "Id" column retains its width
Actual: the "Name" and "Age" column headers switch places, BUT the "Id" column's width is reset to be the same width it was when the page was first loaded.

**Comment by ingshtrom** [comment] 2015-08-23 15:55
This bug is a big problem for our business, so I started work on this without guarantee that it will get merged into the ui-grid official repo. Anywho, I noticed that I can only reproduce this in the Angular app at work and on the ui-grid.info site.  When I run the tutorials locally, I don't run into any problems... I'll keep investigating, but any ideas why this might be happening?

**Comment by ingshtrom** [comment] 2015-08-25 12:44
I cannot close this, but it upon further investigation, this is fixed in the unstable code (which will become v3.0.5).  You can compare the difference in behavior:

bugged: http://ui-grid.info/docs/#/tutorial/401_AllFeatures
works: http://ui-grid.info/docs/#/tutorial/401_AllFeatures

**Comment by tomaslaurutenas** [comment] 2015-08-27 13:29
current version is 3.0.5, but bug is not fixed

**Comment by ingshtrom** [comment] 2015-08-27 13:43
@tomaslaurutenas You need to be more specific with what you are seeing, then. I tested using the stable code on the ui-grid site and have pulled v3.0.5 into my local project. From what I see, it is fixed.

**Comment by tomaslaurutenas** [comment] 2015-08-27 13:49
@ingshtrom yes, it is fixed. sorry, my mistake :)

**Closed** 2015-08-27 13:57 UTC
