### ISSUE TITLE
Chrome 45 Header Not Visible

### ISSUE THREAD

**Issue by CarlSteven** [angular-ui/ui-grid#4376] opened 2015-09-15 17:31 UTC
With Chrome 45 the header is no longer visible due to some CSS issues.
![image](https://cloud.githubusercontent.com/assets/7702743/9884513/bbbf8e18-5ba5-11e5-9641-3dac0601684c.png)

**Comment by AgDude** [comment] 2016-06-24 01:57
I would like to see a plunker demonstrating the issue before merging the linked PR. I haven't looked in detail at the implications, but I suspect there was a reason that overflow was set to hidden (something to do with certain menu configurations)

**Comment by mportuga** [comment] 2016-09-20 19:50
I am currently on Chrome 53 and I cannot reproduce this issue. I am closing it.

**Closed by mportuga** 2016-09-20 19:50 UTC
