### ISSUE TITLE
Unable to compile LESS code from npm package angular-ui-grid (NameError: variable @bootstrapDirectory is undefined)

### ISSUE THREAD

**Issue by tirithen** [angular-ui/ui-grid#4476] opened 2015-10-05 15:05 UTC
Hi, I tried using this project as an npm dependency, there is a less/ directory with a main.less file. When I try to use it as I would when using for example boostrap to override variables I get an error:

```
>> NameError: variable @bootstrapDirectory is undefined in node_modules/angular-ui-grid/less/bootstrap/bootstrap.less on line 30, column 23:
>> 29   // Core variables and mixins
>> 30   @import (reference) "@{bootstrapDirectory}/less/variables.less";
>> 31   @import (reference) "@{bootstrapDirectory}/less/mixins.less";
Warning: Error compiling app/css/main.less Used --force, continuing.
```

My main LESS file looks like this:

```
@import "../../node_modules/angular-ui-grid/less/main";
@import "_ui-grid-variables";
```

And my _ui-grid-variables.less file contains a definition of the @bootstrapDirectory variable like this:

```
@bootstrapDirectory: "../../node_modules/bootstrap";
```

Still the LESS files in the angular-ui-grid package does not compile, why is that? Could it be a problem with the (reference) parameters I am not to familiar with those.

**Comment by crazyjat** [comment] 2016-07-11 19:56
Less in-browser run-time compilation expects a variable to be defined before it is used.  Oddly enough, the less compiler does not have this same expectation. 

ui-grid is simply not setup to easily facilitate using their less files for run-time compliation, which is quite unfortunate and very confusing.

I was able to fix the issue by defining a dummy empty @bootstrapDirectory variable at the top of my main.less file. The problem is that the value of this variable is overridden by ui-grid's variables.less file, which isn't loaded until the very end (look at ui-grid/less/main.less, variable is imported last when it should be first) . So, if you want to customize your @bootstrapDirectory you have to define the variable at the top of the file and then override it to your custom value at the bottom. 

It would be really great if the ui-grid team could make their less files usable for development, but at this time it requires a lot of workarounds.

**Comment by mportuga** [comment] 2016-12-29 22:02
Thank you @crazyjat. I will attempt to make the changes required to make this work.

**Comment by mportuga** [comment] 2018-08-04 19:04
Closed by https://github.com/angular-ui/ui-grid/pull/6825

**Closed by mportuga** 2018-08-04 19:04 UTC
Labels: help wanted
