### ISSUE TITLE
Inverted  Grid

### ISSUE THREAD

**Issue by sameershenai** [angular-ui/ui-grid#4078] opened 2015-07-30 00:58 UTC
In our use case we need the table to be inverted  i.e. new rows are added from bottom-up and scroll bar default position is at the bottom,

For scrollbar we could use scrollTo(lastRowEntity) but rows are still added top to bottom.
One dirty hack i can think of is to add dummy empty rows as padding on top and do some manipulation on each data change.

Is there any cleaner and simpler way to do this ?

**Comment by mportuga** [comment] 2016-12-14 07:06
Closing this as it is not a bug and is old.

**Closed by mportuga** 2016-12-14 07:06 UTC
