### ISSUE TITLE
Only one cell is being allowed per row

### ISSUE THREAD

**Issue by jacohend** [angular-ui/ui-grid#4083] opened 2015-07-30 07:55 UTC
I have 7 columns, one for each day of the week. Each row represents time, so if two data objects have the same time, they are supposed to line up on the same row according to how I have my data ordered. However, I am finding that if a row has a cell, no other cells will line up with that row, and will instead be moved to the next row. 

Each cell is a button with a custom template:

```
<button style="background-color:#08AEBB;color:#ffffff;  text-align:center;position: relative;top: 50%;-webkit-transform: translateY(-50%);-ms-transform: translateY(-50%);transform: translateY(-50%);" class="btn primary" ng-click="grid.appScope.edit(COL_FIELD.id, COL_FIELD.day, COL_FIELD.time, COL_FIELD.route, COL_FIELD.price)">{{COL_FIELD.time}}</br>{{COL_FIELD.route}}</br>{{COL_FIELD.price}}</button>
```

Other than that, there's nothing substantially different than the basic tutorials. I'm not sure why cells in different columns are refusing to share the row.

**Comment by mportuga** [comment] 2016-12-14 07:10
Closing this as it is not a bug and it is old.

**Closed by mportuga** 2016-12-14 07:10 UTC
