### ISSUE TITLE
Cannot read property 'options' of undefined when clicking on GridMenu

### ISSUE THREAD

**Issue by felixn11** [angular-ui/ui-grid#5945] opened 2017-01-12 13:30 UTC
When expanding the GridMenu and error is thrown saying: "Cannot read property 'options' of undefined" @ui-grid.js:18559. This happens when the module 'ui.grid.exporter' is included. 

No need for a Plunkr because the same issue is happening when clicking on the GridMenuButton in the tutorial:
http://ui-grid.info/docs/#/tutorial/206_exporting_data

Seems like grid is undefined in the "shown" event.

**Comment by npetralia** [comment] 2017-01-12 16:24
Hi,

I have open this issue too but nobody look on it
=> https://github.com/angular-ui/ui-grid/issues/5926

**Comment by darionato** [comment] 2017-01-13 14:25
I've this error too

**Comment by npetralia** [comment] 2017-01-13 14:42
It's a regression between 4.0.1 and 4.0.2

**Comment by pkiranc** [comment] 2017-01-25 05:59
This issues is occurring on all the examples that are using menu.Can someone please look into this.

**Comment by dscarfo** [comment] 2017-01-30 15:58
I had the same issue running with version 4.0.2.  Reverting to version 4.0.1 resolved the issue for me.

**Comment by takotuesday** [comment] 2017-02-28 22:46
What is the status of this issue?

**Comment by johnedvard** [comment] 2017-03-20 10:23
I am having the same issue. Everything still works, but the console is overwhelmed with error messages.

**Comment by tmarkley** [comment] 2017-03-24 22:07
Good news: this was fixed in today's release: https://github.com/angular-ui/ui-grid/blob/master/CHANGELOG.md#v403-2017-03-24

**Comment by MJ33** [comment] 2017-03-31 08:07
great! :100:

**Comment by quiksillvr** [comment] 2017-04-04 16:45
Thank you!!

**Comment by darionato** [comment] 2017-04-05 09:04
it works, thanks

**Comment by Kaang** [comment] 2017-12-03 20:36
The same issue in 4.0.11.
4.0.10 looks like works

**Comment by mportuga** [comment] 2018-01-17 04:47
Issue is resolve of 4.2.0

**Closed by mportuga** 2018-01-17 04:47 UTC
