### ISSUE TITLE
Issue in Latest version UI Grid.

### ISSUE THREAD

**Issue by debayan31** [angular-ui/ui-grid#3576] opened 2015-05-25 04:52 UTC
Hi,

While testing with latest version(ui-grid - v3.0.0-rc.21-11b83eb - 2015-05-21) I found some issues mensioned below:

1)When 'Filtering condition is true' , 'scroll down data grid' to some extent, and then try to select any row then highlighted row and selection not aligned.

2) Aggregation Issue.

kindly find screen shot for details.

![not working](https://cloud.githubusercontent.com/assets/11749797/7791951/03c86c08-02c7-11e5-9c3c-1b31a4cb95d8.jpg)
![working](https://cloud.githubusercontent.com/assets/11749797/7791953/03cc7cc6-02c7-11e5-9b1d-1b199daaf0fd.jpg)
![agggn function issue](https://cloud.githubusercontent.com/assets/11749797/7791955/1cc482aa-02c7-11e5-94ec-c5b9b8d70240.jpg)

**Comment by PaulL1** [comment] 2015-05-25 04:59
Item 1. is a duplicate of #3394 

Item 2a. exporting.  This appears to be working on the tutorials http://ui-grid.info/docs/#/tutorial/206_exporting_data.  Are you using the latest release?  What browser are you using?  Do the tutorials work for you?

Item 2b. aggregations.  There are significant code changes in unstable on aggregation.  Are you using that new code base?  I think it makes little sense to try to fix a defect on an older code base, since you'd have to upgrade to unstable to get that fix anyway, and then you'd need to use the new grouping code.

**Comment by debayan31** [comment] 2015-05-25 05:50
Item 1: I found the issue is duplicate but not able to track proposed solution.(enableSelectAll: false is also not woking as expected.)

Item 2a : I am using latest unstable. And it is not working in firefox as well as crome also.

Item 2b:  I had only updated ui-grid-unstable.css and ui-grid-unstable.js latest version.What new code base you are talking about?

**Comment by PaulL1** [comment] 2015-05-25 06:01
Item 1: OK, but it's logged, so no point in raising it again.

Item 2a: is it working on the tutorial?  It is working for me.  If it's working on the tutorial and not in your code, then we need to discuss what is different in your code.

Item 2b: well, I think you'd notice if you had the new grouping code, as it had quite a bit of breaking change in it.

**Comment by debayan31** [comment] 2015-05-25 06:34
Item 2a: Is working in tutorial. And it also working in my code when I am selecting all rows and then "Export visible data as PDF". Code base:

$scope.gridOptions = {
            paginationPageSize: 16,
            saveFocus: false,
            saveScroll: true,
            showGridFooter: false,
            showColumnFooter: true,
            enableFiltering: false,
            modifierKeysToMultiSelectCells: true,
            enableGridMenu: true,
            enableSelectAll: true,
            exporterCsvFilename: 'myFile.csv',
            exporterPdfDefaultStyle: {fontSize: 9},
            exporterPdfTableStyle: {margin: [30, 30, 30, 30]},
            exporterPdfTableHeaderStyle: {fontSize: 10, bold: true, italics: true, color: 'red'},
            exporterPdfHeader: {text: "My Header", style: 'headerStyle'},
            exporterPdfFooter: function (currentPage, pageCount) {
                return {text: currentPage.toString() + ' of ' + pageCount.toString(), style: 'footerStyle'};
            },
            exporterPdfCustomFormatter: function (docDefinition) {
                docDefinition.styles.headerStyle = {fontSize: 22, bold: true};
                docDefinition.styles.footerStyle = {fontSize: 10, bold: true};
                return docDefinition;
            },
            exporterPdfOrientation: 'portrait',
            exporterPdfPageSize: 'LETTER',
            exporterPdfMaxGridWidth: 500,
            exporterCsvLinkElement: angular.element(document.querySelectorAll(".custom-csv-link-location")),
            onRegisterApi: function (gridApi) {
                $scope.gridApi = gridApi;
            }
            //Table Property Ends
        };

Item 2b: Yes I had observed some changes in Grouping grid in new code base.
              But PaUL If you find below screen shot "AGE" is a number type column so in drop down "Agg:min","Agg:max","Agg:count","Agg:avg" is coming. When I am selecting some different Aggregation property then corresponding value are not changing.
I did not find any code changes in Aggregation in new code base (My grid is not a grouping grid).

In "http://ui-grid.info/docs/#/tutorial/401_AllFeatures" example --> Aggregation changes is working fine(This is a example of Grouping Grid).

**Comment by PaulL1** [comment] 2015-05-25 06:48
OK, so on 2a it's working fine in both tutorial and your code?

On 2b, sorry, didn't realise you were talking about footer aggregation.  You'd need to put a breakpoint in the aggregation logic to see what it's doing there.  If you sort after changing the aggregation, does the value then update?  That might indicate it's a problem with when aggregation refreshes the calculations.

**Comment by debayan31** [comment] 2015-05-25 06:55
Item 2a: Kindly look below screen shot for my issue.
![not working](https://cloud.githubusercontent.com/assets/11749797/7793166/9e1d9970-02d8-11e5-98fd-f5f08d45162e.jpg)
![working](https://cloud.githubusercontent.com/assets/11749797/7793165/9e1ca06a-02d8-11e5-81ee-1fa63121ccbb.jpg)


Item 2b: Right It is a problem in footer aggregation when aggregation property is changing.
               If I sort after changing the aggregation, then the value then update accordingly.

**Comment by PaulL1** [comment] 2015-05-25 07:12
For the exporter issues, we'd need a plunker that demonstrates it.  If it's working for you in the tutorial, but not in your code, then logically there's something different in your code.  If you can strip that down so that we can see it in a plunker, then I can work out what it is that causes it.

On the aggregation, I can take a look at that.

**Comment by debayan31** [comment] 2015-05-25 07:57
PauL "exporter issues" is working , Issue is coming for browser issue.Now it is resolved.

Kindly update me If any changes done on aggregation issue and Header alignment.

**Comment by PaulL1** [comment] 2015-05-27 01:39
Where are you getting the menu items of 'agg: min' etc from?  Are you manually creating them, or is there some functionality in the grid that makes them available?  I can't see them anywhere.

**Comment by debayan31** [comment] 2015-05-27 05:48
Header alignment is fixed. In latest release "ui-grid - v3.0.0-rc.21-3597417 - 2015-05-27" previous issue (#3319 ) reoccurred.
#3319 --> Filter Part Is not opening.

agg: min is coming for any number type column as given in screen shot.

![agg part](https://cloud.githubusercontent.com/assets/11749797/7829623/eddb7d6c-0461-11e5-8684-26e41fb9c58d.jpg)

**Comment by debayan31** [comment] 2015-06-03 10:55
Hi paul,

In latest release "ui-grid - v3.0.0-rc.21-3597417 - 2015-05-27" , same problem is coming for Grouping Grid also.

**Comment by debayan31** [comment] 2015-06-05 12:46
Header alignment is fixed in latest version.

**Comment by PaulL1** [comment] 2015-11-18 07:18
No progress in some time, I think the underlying issues are fixed.  Closing.

**Closed by PaulL1** 2015-11-18 07:18 UTC
Labels: waiting-response
