### ISSUE TITLE
grid.appScope and Controller As

### ISSUE THREAD

**Issue by crazyjat** [angular-ui/ui-grid#4116] opened 2015-08-04 21:02 UTC
When using Controller As in Angular, I would expect that grid.appScope would point to this of the controller, yet it always points to $scope. If I have my methods defined on this of the controller, how can I gain access to those methods in a cellTemplate?

**Comment by lebolo** [comment] 2015-08-04 22:21
You can use [`appScopeProvider`](http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions) (mentioned in http://ui-grid.info/docs/#/tutorial/305_appScope) to pass a reference `this`.

**Comment by AngularRocks** [comment] 2015-09-15 12:22
Any solution on this?

**Comment by AngularRocks** [comment] 2015-09-15 12:42
its working  as suggested by lebolo. got resolved with statement

vm.gridOptions.appScopeProvider = this;
this.functionName= function ($event) {

**Comment by nkoterba** [comment] 2015-10-02 01:42
@AngularRocks If you're using `ControllerAs` syntax, usually you rename this as a variable (often `vm`) as you show in your example above.  Thus, instead of passing `this` you probably want to pass `vm`. 

See below.

```javascript
vm.gridOptions.appScopeProvider = vm;
vm.functionName= function ($event) {
```

**Comment by jweinstein92** [comment] 2015-12-19 15:14
I'm having issues with this as well on version 3.0.7. I have tried what was posted above with no luck. I am trying to add a RowHeaderColumn to the grid and have a callback method triggered on click.

```
var vm = this;
vm.editTour = function(row) {
    var foo = 1;
};
vm.gridOptions.appScopeProvider = vm;
vm.gridOptions.onRegisterApi = function(gridApi){
    //set gridApi on scope
    vm.gridApi = gridApi;
    var cellEditTemplate = 'grid-header-edit.tmpl.html';
    vm.gridApi.core.addRowHeaderColumn( { name: 'rowHeaderCol', displayName: '', width: 30, cellTemplate: cellEditTemplate} );
};
```

In cell template I have tried the following with no luck. Any ideas? I also tried setting appScopeProvider = this.
```
<div ng-click="grid.appScope.edit(row)">
    <i class="zmdi zmdi-edit"></i>
</div>

<div ng-click="vm.grid.appScope.edit(row)">
    <i class="zmdi zmdi-edit"></i>
</div>

<div ng-click="grid.appScope.vm.edit(row)">
    <i class="zmdi zmdi-edit"></i>
</div>
```

**Comment by nkoterba** [comment] 2015-12-20 00:10
I'm using 3.0.7 and your code above looks similar to mine.

However, I create the grid options object and then assign it to vm.gridOptions.  I don't think it should have any different behavior than what you have above, but you might try it.

So I have:
```javascript
var vm = this;
vm.gridOptions = createGridOptions();

function createGridOptions() {
      return {
				rowHeight: rowHeight,

				// Set scope provider to vm since we're using ControllerAs syntax
				appScopeProvider: vm,

				// Register for callbacks and to perform grid functions
				onRegisterApi: function (gridApi) {
					vm.gridApi = gridApi;
                }  
       }
}

vm.renderRow = function (entity) {
    // ...
}
```

My html then looks like:
```html
<div class="ui-grid-cell-contents" title="{{row.entity.line}}"
     ng-bind-html="grid.appScope.renderRow(row.entity)">
</div>
```

**Comment by agupta-q4** [comment] 2016-10-07 08:47
In case of using ES6 `class` syntax for controller, it would be simply as below:

```
class MyCtrl {
  constructor() {
    this.gridOption = {
      data: [],
      appScopeProvider: this
    }
  }
}
```

**Comment by mportuga** [comment] 2016-12-14 07:35
Closing as this is not a bug.

**Closed by mportuga** 2016-12-14 07:35 UTC
Labels: type: FAQ, waiting-response

**Comment by chris-trotter** [comment] 2017-03-27 21:31
For anyone using Angular 1.5 components and the this keyword. 
Use after your main gridOptions object definition, or you'll get an undefined on this.gridOptions.

`this.gridOptions.appScopeProvider = this;`

If you're using the gridApi. Bind the function to the component using `.bind(this)`. Bind the component scope to the gridAPI methods using `.call(this, null).`

```
this.gridOptions.onRegisterApi = function (gridApi) {
      this.gridApi = gridApi;
      gridApi.selection.on.rowSelectionChanged.call(this, null, function (row) {
        modal(row.entity);
      });
    }.bind(this);
```

**Comment by dejaneves** [comment] 2018-06-12 16:39
after a long time, but it worked for me, thanks

**Comment by samarulrajt** [comment] 2019-05-28 13:07
> I'm using 3.0.7 and your code above looks similar to mine.
> 
> However, I create the grid options object and then assign it to vm.gridOptions. I don't think it should have any different behavior than what you have above, but you might try it.
> 
> So I have:
> 
> ```js
> var vm = this;
> vm.gridOptions = createGridOptions();
> 
> function createGridOptions() {
>       return {
>                 rowHeight: rowHeight,
> 
>                 // Set scope provider to vm since we're using ControllerAs syntax
>                 appScopeProvider: vm,
> 
>                 // Register for callbacks and to perform grid functions
>                 onRegisterApi: function (gridApi) {
>                     vm.gridApi = gridApi;
>                 }  
>        }
> }
> 
> vm.renderRow = function (entity) {
>     // ...
> }
> ```
> 
> My html then looks like:
> 
> ```
> <div class="ui-grid-cell-contents" title="{{row.entity.line}}"
>      ng-bind-html="grid.appScope.renderRow(row.entity)">
> </div>
> ```

Again i want to have a function inside the bind-html. i tried it but i could not trigger a function inside. Can you help in that ? Thanks
