### ISSUE TITLE
page selector in http://ui-grid.info/docs/#/tutorial/314_external_pagination 

### ISSUE THREAD

**Issue by bayy** [angular-ui/ui-grid#2523] opened 2015-01-09 15:59 UTC
On http://ui-grid.info/docs/#/tutorial/314_external_pagination

![screen shot 2015-01-09 at 8 56 57 am](https://cloud.githubusercontent.com/assets/2373656/5682490/89b98400-97dd-11e4-9ec4-86e3c3d6bfab.png)
Starting with page 1 selected, when typing in any number 1,2,3,5, etc in the input box, the number in the input box becomes 4.

**Comment by PaulL1** [comment] 2015-01-10 20:54
@brianchance: any thoughts on this?

**Comment by brianchance** [comment] 2015-01-10 21:00
It checks if you go over the number of pages, if so, it resets to the last page. Same code that checks if you are on page 4 with 25 per page, then change to 50 per page. You should be on page 2 then.

**Comment by bayy** [comment] 2015-01-10 21:04
@brianchance, what you are saying is that when I typing in any number 1, 2,3,5 etc, what I have entered is in fact 11, 12, 13, 15, and then the code checks whether the number is over 4 and then resets it to 4. Is my understanding right?

**Comment by brianchance** [comment] 2015-01-10 21:05
yes.

**Comment by bayy** [comment] 2015-01-10 21:06
Then it is the same problem with #2518

**Comment by brianchance** [comment] 2015-01-10 21:08
If you enter more than the allowed number of pages, what would you want the behavior to be? Send a bad value to the server?

**Comment by bayy** [comment] 2015-01-10 21:13
I apologize if I misunderstand you, @brianchance , but you sound that you are offended.  I just pointed out what the problem and confusions caused. I did not say anything bad.

**Comment by brianchance** [comment] 2015-01-10 22:11
Not offended, but what would the expected behavior be if the user changes to a value that is above the max pages or below one? You said it is a problem, but what would be a solution?

On #2518, I agree, it could use debounce, but that is an angular 1.3 feature while the ui-grid supports 1.2. We could put an ngModelOptions on the element that would only work for 1.3, but the main contributors (@PaulL1) would need to decide if that is appropriate.

You can supply your own pager as a template, just copy the existing one and make any changes you need.

**Comment by bayy** [comment] 2015-01-10 22:22
@brianchance , I appreciate your reply.

The problem is that when a user entered a valid value, in this case, 2 or 3, they would expect to see page 2 or 3. However, the number is automatically changed to 4. This is very confusing. With your explanation, now I understand that after entering 2 or 3, the real value is in fact 12 or 13, which is above the maximum allowed value 4. 

As you mentioned, a new pager could be used in which it only triggers a page reload after a button click, not with every keystroke.

**Comment by PaulL1** [comment] 2015-01-11 00:34
If the problem is that you enter 2 or 3, and it actually goes to 13 or 14, I assume the only reason that the user doesn't notice is that the pager text box isn't very big, so they can't see the 1.  If that is the cause, then a solution would be to automatically select the text in the box on gaining focus, then when you type 2 you get 2 and not 12.

Is that what we're all talking about, or are we talking about different things?

**Comment by bayy** [comment] 2015-01-11 03:11
When you enter 2, 3, or any number in the input box, it is immediately changed to 4. There is no way a user can understand why it is changed. 

"a solution would be to automatically select the text in the box on gaining focus, then when you type 2 you get 2 and not 12." This will work for single number page, but not page 23 or 456 because the current implementation reload page with every keystroke.

**Comment by brianchance** [comment] 2015-01-12 14:12
We use the angular-ui bootstrap pagination directive (http://angular-ui.github.io/bootstrap/#/pagination).

You can override the pager template globally in an app.run... (the template name assumes you are using the very latest unstable that merged pager and pagination)
```
$templateCache.put('ui-grid/pagination',
    '<div class="ui-grid-pager-panel" ui-grid-pager ng-show="grid.options.enablePaginationControls">' +
        '<div class="ui-grid-pager-container">' +
            '<div class="ui-grid-pager-control">' +
                '<pagination class="pagination-sm" total-items="grid.options.totalItems" items-per-page="grid.options.paginationPageSize" ng-model="grid.options.paginationCurrentPage" boundary-links="true" max-size="5"></pagination>' +
            '</div>' +
            '<div class="ui-grid-pager-row-count-picker">' +
                '<select ng-model="grid.options.paginationPageSize" ng-options="o as o for o in grid.options.paginationPageSizes"></select>' +
                '<span class="ui-grid-pager-row-count-label">&nbsp;{{sizesLabel}}</span>' +
            '</div>' +
        '</div>' +
        '<div class="ui-grid-pager-count-container">' +
            '<div class="ui-grid-pager-count">' +
                '<span ng-show="grid.options.totalItems > 0">' +
                    '{{showingLow}} - {{showingHigh}} of {{grid.options.totalItems}} {{totalItemsLabel}}' +
                '</span>' +
            '</div>' +
        '</div>' +
    '</div>'
  );
}]);
```

**Comment by ran85** [comment] 2016-05-16 15:19
Hi. 
Maybe  it is not directly related with this. 
I am using ui-grid with enablePaginationControls=false, but during profiling on page change,I saw that it trashes the layout (forces re style and layout), though the ui-grid-pager-panel div  is display:none !important . On IE11 it takes some time... Is it supposed to be this way ?

**Closed** 2018-01-18 04:44 UTC
Labels: type: bug
