### ISSUE TITLE
Minified file size too big

### ISSUE THREAD

**Issue by hybmg57** [angular-ui/ui-grid#4099] opened 2015-08-01 07:30 UTC
Minified file is like 300kb. Is there a way to separate them so you have something like 'core', 'export-csv', 'grouping' etc.

**Comment by swalters** [comment] 2015-08-04 19:17
This is something that is on the roadmap.  Would be great if a grunt expert jumped in and created a PR to do this.

**Comment by JLLeitschuh** [comment] 2015-08-04 20:20
I'll probably take a crack at this at some point but I don't have time right now. If anyone beats me to it I don't mind.

**Comment by hybmg57** [comment] 2015-08-05 08:54
Probably need gulp version also

**Comment by Robinson7D** [comment] 2015-08-05 12:55
Should not need both. Grunt alone will suffice.

**Comment by mportuga** [comment] 2016-12-14 07:21
Closing as this is a duplicate of #3421

**Closed by mportuga** 2016-12-14 07:21 UTC
Labels: PRs plz!, type: build
