### ISSUE TITLE
Not Responsive for small screen devices like mobile, tablet etc 

### ISSUE THREAD

**Issue by AbdulShaikh** [angular-ui/ui-grid#5989] opened 2017-02-07 06:41 UTC
Using the latest version 4.0 of the ui-grid and it's very sad to hear that it not displaying correctly in mobile devices, In mobile data is getting cut and display the data in incorrect position/alignment as well as no option to use <table> if will want to use it.

**Comment by mportuga** [comment] 2018-04-01 02:38
Duplicate of #4253 and #2599

**Closed by mportuga** 2018-04-01 02:38 UTC
