### ISSUE TITLE
custom checkbox in ui-grid doesn't work properly

### ISSUE THREAD

**Issue by flamant** [angular-ui/ui-grid#4749] opened 2015-11-21 16:34 UTC
Hi,

I implemented a grid with two level of grouping.  You can see the plunker here: 
http://plnkr.co/edit/jY0lH1FsczgR3jrQH3iL?p=preview

I am facing two problems

1) first when I am expanding the first grouping level (for example N° CF = 1000(4)) and when I check the checkbox on the second level grouping, it goes to "manageClick" handler and I can see in the log that row.entity.checkbox=undefined. It is surprising because when I inspect row in firebug it has a property entity and in entity I can see the property checkbox. Furthermore I have not this issue in my application. It is only in the plunker that it happens.
2) The second issue (that I can see in my application but until now not in the plunker because of the first issue) is when I open just the first grouping level (for example N° CF = 1000(4)) and when I I toggle the checkbox to true in the second level of grouping , and then I expand this row, the chidren are selected (as managed in "manageClick" function) but the second grouping level that I previously checked to true, becomes unselected whereas it shoud stay selected

Thank you in advance for your answers

**Comment by flamant** [comment] 2015-11-22 09:56
Hello,

I found a solution. Instead of putting 
{ name: 'checkbox',field: 'checkbox', displayName: 'checkbox' , width: '2%' , cellTemplate: '<div  > <INPUT ng-if="row.treeLevel != 0" type="checkbox" ng-model="row.entity.checkbox" ng-click="grid.appScope.manageClick(row)" >{{row.treeLevel}}</div>' },

I put
{ name: 'checkbox',field: 'checkbox', displayName: 'checkbox' , width: '2%' , cellTemplate: '<div  > <INPUT ng-if="row.treeLevel != 0" type="checkbox" ng-model="row.checkbox" ng-click="grid.appScope.manageClick(row)" >{{row.treeLevel}}</div>' },

So actually I replace the value of ng-model of my checkbox from row.entity.checkbox to row.checkbox

I don't know why, when I expanded a grouping row,  the row.entity was refreshed and I lost the row.entity.checkbox value.

Do you know why ?

**Comment by imbalind** [comment] 2015-11-22 18:59
Issue number 1 is quite strange, can you reproduce it on your sistem too or only on plunkr? Because I found plunker to be work quite bad when using custom templating in ui-grid

**Comment by flamant** [comment] 2015-11-23 20:06
Hello imbalind. Thank you for your answers. I cannot reproduce it on my system

**Comment by imbalind** [comment] 2015-11-25 08:03
Ok, then I'll close this as it seems more of a plunker bug. If you need to have it working on plunker you should file an issue on their repository.

**Closed by imbalind** 2015-11-25 08:03 UTC
Labels: grid-grouping, needs: answer
