### ISSUE TITLE
Filtering not working with ui-grid-selection

### ISSUE THREAD

**Issue by CaosZero** [angular-ui/ui-grid#6191] opened 2017-05-03 13:03 UTC
I have defined grid in this way : 
`  <div
            style="height: 580px"
            ui-grid="gridOptions"
            ui-grid-cellNav 
            ui-grid-selection
            ui-grid-exporter
            ui-grid-pagination
            ui-grid-grouping 
            ui-grid-pinning
            ui-grid-auto-resize
            ui-grid-resize-columns
            ui-grid-move-columns> `

Filtering not working if I declare in grid following directive " ui-grid-selection". When I delete it, filtering and othere components working perfectly.
Provide [plunk ](http://plnkr.co/edit/qkGaqHEnIs2Rh6YwD6A1?p=preview)for more test.

**Comment by Bodmoor** [comment] 2017-05-03 14:20
I have a similar issue where I want to toggle filtering dynamically. When I disable selection I can do this, but when I enable selection toggling the filters only works if I initially have them enabled.

the below only works if my initial gridoptions have enablefiltering set to true.

``` javascript  
mc.gridOptions.enableFiltering = true / false;
scope.gridApi.core.notifyDataChange(globalUiGridConstants.dataChange.ALL);
```

**Comment by CaosZero** [comment] 2017-05-03 14:45
@Bodmoor in my case I have filters  enabled initially, but the stranger thing is that if I do pin of columns, the filters resume to working. So I suppose that something have to be notified about some changes ..

**Comment by Bodmoor** [comment] 2017-05-03 14:53
If I disable enableRowHeaderSelection it does work. But I think it is a browser issue with the rowheader height since it only occurs in IE for me.

**Comment by AgDude** [comment] 2017-11-09 21:36
This is a duplicate of #3705

**Closed** 2018-03-20 21:42 UTC
