### ISSUE TITLE
The grid moves up and down

### ISSUE THREAD

**Issue by quin810** [angular-ui/ui-grid#2930] opened 2015-03-06 13:46 UTC
When the browser does not display a vertical scrollbar the grid goes into an infinite loop of moving up and down.  

Details:
The grid has the auto-resize directive set.  

The grid has the row-select directive set.

The grid has both a header and footer.

Grid+Page Content does not fill the page.

When the browser window is resized the grid resize event fires.

If the new grid size is smaller than the new window size, but the grid is temporarily larger than the              window size, the browser resize bar triggers and infinite loop of resize events.

Forcing the vertical scrollbar to appear on the page at all times is a work-around for preventing this issue from occurring. 

This issue reproducible in IE 9 and Chrome Version 39.0.2171.71 m.  It does not seem to be an issue in later versions of IE.

![griddown](https://cloud.githubusercontent.com/assets/7606357/6526063/74ac8d30-c3db-11e4-8cec-d16bf48bd73f.jpg)
![gridup](https://cloud.githubusercontent.com/assets/7606357/6526062/74aa70ae-c3db-11e4-9d7b-264d8d8cea71.jpg)

**Comment by killyosaur** [comment] 2015-03-06 13:53
I've also seen this intermittently in IE 11 and it seems to be fairly consistent in Chrome. I think it plays into how chrome and IE handle the dynamic scroll bar, the only place I haven't been able to reproduce the error is in Firefox. The issue may also have something to do with having multiple elements on a page that can be expanded/collapsed dynamically which would also affect the dynamic scroll bar.

**Comment by killyosaur** [comment] 2015-03-06 16:51
Clarification: IE11 only causes the dancing grid resize issue when it is set to IE9 or lower mode.

**Comment by PaulL1** [comment] 2015-03-28 20:42
I'm hoping that the resizing changes I've done may fix this, although it's hard to say as I don't have a reliable recreate.  Could someone create a plunker showing the problem (then I'll work to fix it), or alternatively confirm that it's no longer occurring?

**Comment by c0bra** [comment] 2015-03-30 21:09
Here's a plunker demonstrating the issue. If you click the button a few times you'll see it.

This happens to me in IE11, Chrome, and FF.

**Comment by JLLeitschuh** [comment] 2015-06-19 01:30
This seems to be fixed in the current version.

**Closed** 2018-03-24 04:11 UTC
Labels: type: bug
