### ISSUE TITLE
ngGridEventColumns for ui grid?

### ISSUE THREAD

**Issue by shash8787** [angular-ui/ui-grid#4274] opened 2015-08-26 16:48 UTC
Is there an event which is fired always whenever I interact with ui-grid like when I group, sort, or filter? I'm using this event to persist the state of the grid and reload it when the user refreshes the page or comes back. Any help would be greatly appreciated.

Thanks

**Comment by hboylan** [comment] 2015-08-27 14:05
Here you are good sir: https://github.com/angular-ui/ui-grid/wiki/Grid-Events

**Comment by shash8787** [comment] 2015-08-28 18:42
Thanks but these events are for ng-grid and I don't see being fired or mentioned any where in ui-grid code.

**Comment by hboylan** [comment] 2015-08-28 21:50
You are correct! My bad, these are what I'm using for sorting, pagination, and selection.

```javascript
grid.gridApi.core.on.sortChanged($scope, function(g, sortColumns){})
grid.gridApi.pagination.on.paginationChanged($scope, function(currentPage, pageSize){})
grid.gridApi.selection.on.rowSelectionChangedBatch($scope, function(rows){})
```

**Comment by adineag** [comment] 2016-10-16 11:42
Is there any event which triggers when the columns are rearranged (not sorted) ?

**Comment by mportuga** [comment] 2016-12-14 07:41
Closing as this is not a bug.

**Closed by mportuga** 2016-12-14 07:41 UTC
