### ISSUE TITLE
scrollToFocus does not enable edit when enableCellEditOnFocus is set to true

### ISSUE THREAD

**Issue by moses-seeq** [angular-ui/ui-grid#5417] opened 2016-05-19 01:38 UTC
When enableCellEditOnFocus is set to true, I expect that scrollToFocus will enable a cell's edit mode.  However, it does not.  In this plunker, which was taken from the cellNav examples and modified to add cellEdit, you can see that when clicking 'Focus Row 50, Balance' that it is merely highlighted.  If you click into another balance first, the edit mode displays when clicking 'Focus Row 50, Balance'.

http://plnkr.co/edit/XTskI7y9CBsq5aBY8mSv?p=preview

**Comment by bjaraujo** [comment] 2016-06-10 09:43
I think this has to do with grid not ready (still scrolling) when edit is requested. scrollToFocus probaly needs to put some sort of the timeout when calling focus.

**Comment by AlexanderKheimonen** [comment] 2017-12-28 16:59
It has nothing to do with timeout. The problem is with 'if' condition here: https://github.com/angular-ui/ui-grid/blob/bcbd8433dcb8e69d13ea4281f426febf226986aa/src/features/edit/js/gridEdit.js#L537

evt parameter is undefined when scrollToFocus is used. So 'if' condition evaluates to false and beginEdit never gets called.
Can anybody provide some workaround?

**Comment by tomo357349** [comment] 2018-01-15 08:12
It occurs in version 4.0.8 or later. (bcbd8433)

**Comment by mportuga** [comment] 2018-04-05 15:41
I believe this issue is resolved in the latest version of ui-grid

**Closed by mportuga** 2018-04-05 15:41 UTC
