### ISSUE TITLE
UI GRID expand/collapse rows

### ISSUE THREAD

**Issue by uideveloperui** [angular-ui/ui-grid#5318] opened 2016-04-13 15:23 UTC
I am using ui-grid-tree-view and $$treeLevel = 0 to make a row as a parent/expandale. However i have a requirement that when the user clicks on the down arrow/drill down on the parent/expand a row the child items should show the row numbers in in above image. How can i achieve it ?

![image](https://cloud.githubusercontent.com/assets/18422863/14498872/1c1fbd90-016a-11e6-9663-3cb241c0b5f6.png)

**Comment by billyaraujo** [comment] 2016-04-21 09:31
Duplicate of #5318

**Closed** 2017-12-22 05:35 UTC
