### ISSUE TITLE
Row selection check-mark issue

### ISSUE THREAD

**Issue by BMK91** [angular-ui/ui-grid#6593] opened 2018-03-09 06:10 UTC
Hi guyz,

I think there's some minor mistake for row selection.
http://plnkr.co/edit/5F6tuNuft7QDhxgKCRPy?p=preview
When no data provided to grid, all selection checkbox remains checked.

Thanks.

**Comment by mportuga** [comment] 2018-03-10 18:29
Hi, could you help me understand how that is a problem?

**Comment by mportuga** [comment] 2018-03-12 19:52
This is a duplicate of #6582

**Closed by mportuga** 2018-03-12 19:52 UTC
Labels: waiting-response
